<?php
require __DIR__.'/lib/bootstrap.php';
if($config['demo_mode']){header('Location: index.php');exit;}
$error='';$done=false;$pdo=null;try{$pdo=db();}catch(Throwable $e){$error='Database produksi belum siap. Periksa driver PDO MySQL, kredensial, dan schema.';}
if(!$pdo&&!$error){$error='Database belum tersedia. Import database/schema_enterprise.sql lalu periksa konfigurasi.';}
$count=0;if($pdo){try{$count=(int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn();}catch(Throwable $e){$error='Schema belum lengkap: '.$e->getMessage();}}
if($count>0){header('Location: login.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&!$error){try{verifyCsrf();$name=trim((string)($_POST['name']??''));$email=strtolower(trim((string)($_POST['email']??'')));$pass=(string)($_POST['password']??'');$key=(string)($_POST['setup_key']??'');if($config['setup_key']!==''&&!hash_equals($config['setup_key'],$key))throw new RuntimeException('Setup key tidak valid.');if(strlen($name)<3||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($pass)<12)throw new RuntimeException('Nama/email tidak valid atau password kurang dari 12 karakter.');$st=$pdo->prepare("INSERT INTO users(name,email,password_hash,role,is_active) VALUES(?,?,?,'group_owner',1)");$st->execute([$name,$email,password_hash($pass,PASSWORD_DEFAULT)]);$done=true;}catch(Throwable $e){$error=$e->getMessage();}}
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Setup · NEXA Group Finance</title><link rel="stylesheet" href="assets/app.css?v=3"></head><body class="auth-body"><main class="auth-shell single"><section class="auth-card"><div><span class="eyebrow">ONE-TIME SETUP</span><h2>Buat Group Owner</h2><p>Halaman ini otomatis terkunci setelah user pertama berhasil dibuat.</p></div><?php if($done):?><div class="auth-success">Akun owner berhasil dibuat. <a href="login.php">Masuk sekarang →</a></div><?php else:?><?php if($error):?><div class="auth-error"><?=e($error)?></div><?php endif?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><label>Nama<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Password kuat<input type="password" name="password" minlength="12" required></label><?php if($config['setup_key']!==''):?><label>Setup Key<input type="password" name="setup_key" required></label><?php endif?><button class="primary-btn full" type="submit">Buat Owner Pertama</button></form><?php endif?></section></main></body></html>
