<?php
declare(strict_types=1);
$root=dirname(__DIR__);$required=[
 'src/Application/EnterpriseKernel.php','src/Accounting/JournalEntry.php','src/Revenue/DailyIncomePostingService.php',
 'src/ARAP/PaymentAllocationService.php','src/Banking/ReconciliationService.php','src/Consolidation/EliminationService.php',
 'src/Tax/TaxCalculator.php','src/FX/FxCalculator.php','src/Assets/DepreciationService.php','src/Reports/StatementService.php',
 'database/migrations/20260925_v6_enterprise_r3.sql','database/migrations/20260926_v7_enterprise_r4.sql','database/migrations/20260926_v8_finance_operations.sql','database/migrations/20260926_v9_enterprise_usability.sql','database/migrations/20260926_v10_group_finance_controls.sql','database/schema_enterprise_r7.sql','lib/r4_runtime.php','lib/r5_runtime.php','lib/r6_runtime.php','lib/r7_runtime.php','assets/r4-ui.js','assets/r5-ui.js','assets/r6-ui.js','assets/r7-ui.js','src/Security/RbacService.php','src/Reports/SqlReportService.php','src/Audit/TransactionalAuditService.php','src/Expense/DailyExpenseService.php','src/Treasury/BankTransferService.php','src/Treasury/CashForecastService.php','src/Recurring/RecurringJournalService.php','src/Onboarding/OpeningBalanceService.php','src/Closing/YearEndCloseService.php','src/Advance/EmployeeAdvanceService.php','src/Financing/LoanService.php','src/Equity/EquityTransactionService.php','src/Planning/BudgetScenarioService.php','src/Notifications/NotificationService.php','src/Reports/ManagementKpiService.php'
];$fail=0;foreach($required as $file){$ok=is_file($root.'/'.$file)&&filesize($root.'/'.$file)>100;echo($ok?'PASS':'FAIL')."  {$file}\n";if(!$ok)$fail++;}
$phpFiles=[];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root.'/src'));foreach($it as $f)if($f->isFile()&&$f->getExtension()==='php')$phpFiles[]=$f->getPathname();echo "INFO  enterprise PHP modules: ".count($phpFiles)."\n";if(count($phpFiles)<30){echo "FAIL  modularity floor not met\n";$fail++;}else echo "PASS  modularity floor met\n";exit($fail?1:0);
