import { chromium } from 'playwright';
const base=process.env.NEXA_TEST_BASE_URL||'http://127.0.0.1:8080';
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});
const must=async(c,n)=>{if(!c)throw new Error('FAIL '+n);console.log('PASS '+n)};
await page.goto(base+'/login.php');await page.locator('input[name=email]').fill('owner-ci@nexa.local');await page.locator('input[name=password]').fill('ProductionTest!2026');await page.locator('button[type=submit]').click();await page.waitForURL(/index\.php/);await must((await page.locator('body').innerText()).includes('NEXA'),'login owner');
const pages={dashboard:'Executive',companies:'Badan Usaha',organization:'Cabang & Departemen',coa:'Chart of Accounts',parties:'Customer & Vendor','daily-income':'Pendapatan Harian','daily-expense':'Pengeluaran Harian',treasury:'Treasury',advances:'Uang Muka & Reimbursement',financing:'Pinjaman & Modal',automation:'Jurnal Berulang',onboarding:'Saldo Awal',imports:'Import & Onboarding',documents:'Dokumen & Bukti',transactions:'Transaksi',approvals:'Approval',arap:'AR / AP',reconciliation:'Rekonsiliasi',periods:'Closing',reports:'Laporan Keuangan',cashbank:'Cash & Bank',budget:'Budget',planning:'Budget Scenario & Forecast',assets:'Aset',intercompany:'Intercompany',tax:'Pajak',fx:'Multi-Currency',analytics:'Analytics',notifications:'Notification Center',integrations:'Integrasi',backup:'Backup',audit:'Audit',settings:'Pengaturan'};
for(const [slug,text] of Object.entries(pages)){await page.goto(base+`/index.php?page=${slug}`);await must((await page.locator('body').innerText()).includes(text),`page ${slug}`);}
await page.goto(base+'/index.php?page=dashboard');await must(await page.locator('canvas').count()>=2,'dashboard charts rendered');
await page.locator('#themeBtn').click();await must(await page.locator('body').evaluate(el=>el.classList.contains('dark')),'dark mode toggle');
await page.goto(base+'/index.php?page=daily-income');await must(await page.locator('#dailyIncomeCompany').count()===1,'daily income company selector');await must(await page.locator('.r4-income-amount').count()>=1,'daily income categories render');


await page.goto(base+'/index.php?page=daily-expense');await must(await page.locator('#dailyExpenseCompany').count()===1,'daily expense company selector');await must(await page.locator('.r5-expense-amount').count()>=1,'daily expense categories render');
await page.goto(base+'/index.php?page=treasury');await page.getByRole('button',{name:/Transfer Rekening/}).click();await must(await page.locator('#r4Modal.open').count()===1,'treasury transfer modal opens');await page.getByRole('button',{name:'Batal'}).click();
await page.goto(base+'/index.php?page=automation');await page.getByRole('button',{name:/Template Recurring/}).click();await must(await page.locator('#r4Modal.open').count()===1,'recurring journal modal opens');await page.getByRole('button',{name:'Batal'}).click();
await page.goto(base+'/index.php?page=onboarding');await page.getByRole('button',{name:/Saldo Awal/}).click();await must(await page.locator('#r4Modal.open').count()===1,'opening balance modal opens');await page.getByRole('button',{name:'Batal'}).click();
await page.goto(base+'/index.php?page=coa');await page.getByRole('button',{name:/Akun Baru/}).click();await must(await page.locator('#r4Modal.open').count()===1,'COA enterprise modal opens');await page.getByRole('button',{name:'Batal'}).click();
await page.goto(base+'/index.php?page=arap');await page.getByRole('button',{name:/Invoice/}).first().click();await must(await page.locator('#r4Modal.open').count()===1,'Invoice enterprise modal opens');await page.getByRole('button',{name:'Batal'}).click();
await page.goto(base+'/index.php?page=assets');await page.getByRole('button',{name:/Aset/}).first().click();await must(await page.locator('#r4Modal.open').count()===1,'Asset enterprise modal opens');await page.getByRole('button',{name:'Batal'}).click();

await page.goto(base+'/index.php?page=advances');await page.getByRole('button',{name:/Uang Muka/}).first().click();await must(await page.locator('#r4Modal.open').count()===1,'employee advance modal opens');await page.getByRole('button',{name:'Batal'}).click();
await page.goto(base+'/index.php?page=financing');await page.getByRole('button',{name:/Pinjaman/}).first().click();await must(await page.locator('#r4Modal.open').count()===1,'loan modal opens');await page.getByRole('button',{name:'Batal'}).click();await page.getByRole('button',{name:/Modal \/ Dividen/}).click();await must(await page.locator('#r4Modal.open').count()===1,'equity modal opens');await page.getByRole('button',{name:'Batal'}).click();
await page.goto(base+'/index.php?page=planning');await page.getByRole('button',{name:/Scenario/}).first().click();await must(await page.locator('#r4Modal.open').count()===1,'budget scenario modal opens');await page.getByRole('button',{name:'Batal'}).click();
await page.goto(base+'/index.php?page=notifications');await must((await page.locator('body').innerText()).includes('Notification Center'),'notification center renders');
await page.screenshot({path:'artifacts/dashboard.png',fullPage:true});
await page.goto(base+'/index.php?page=reports&report_view=pl');await page.screenshot({path:'artifacts/report-pl.png',fullPage:true});await page.goto(base+'/index.php?page=reports&report_view=equity');await must((await page.locator('body').innerText()).includes('Perubahan Ekuitas'),'equity statement renders');await page.screenshot({path:'artifacts/report-equity.png',fullPage:true});
await browser.close();console.log('PASS browser E2E UAT');
