<?php
declare(strict_types=1);
require_once __DIR__.'/../src/autoload.php';
$config = require __DIR__.'/../config/config.php';
date_default_timezone_set($config['timezone']);
ini_set('session.use_strict_mode','1'); ini_set('session.use_only_cookies','1'); ini_set('session.cookie_httponly','1'); ini_set('session.cookie_samesite','Lax'); if(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')ini_set('session.cookie_secure','1');
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
if(PHP_SAPI!=='cli'&&!headers_sent()){header('X-Content-Type-Options: nosniff');header('X-Frame-Options: DENY');header('Referrer-Policy: no-referrer');header('Permissions-Policy: camera=(), microphone=(), geolocation=()');header('Cache-Control: no-store, private');}

function e(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function money(float|int $v): string { return 'Rp '.number_format((float)$v,0,',','.'); }
function pct(float $v): string { return number_format($v,1,',','.').'%' ; }
function textLength(string $v): int { return function_exists('mb_strlen') ? mb_strlen($v,'UTF-8') : strlen($v); }
function textTail(string $v,int $n): string { return function_exists('mb_substr') ? mb_substr($v,-$n,null,'UTF-8') : substr($v,-$n); }
function jsonOut(array $data, int $status=200): never { http_response_code($status); header('Content-Type: application/json; charset=utf-8'); echo json_encode($data, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function csrf(): string { if(empty($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(24)); return $_SESSION['csrf']; }
function verifyCsrf(): void { $t=(string)($_POST['csrf'] ?? $_SERVER['HTTP_X_CSRF_TOKEN'] ?? ''); if(!$t || !hash_equals($_SESSION['csrf']??'', $t)) throw new RuntimeException('CSRF token tidak valid.'); }
function db(): ?PDO {
    static $initialized=false, $pdo=null;
    global $config;
    if($config['demo_mode']) return null;
    if($initialized) return $pdo;
    $initialized=true;
    if(!in_array('mysql', PDO::getAvailableDrivers(), true)){
        throw new RuntimeException('PDO MySQL tidak tersedia pada server. Aktifkan extension pdo_mysql sebelum menjalankan mode produksi.');
    }
    $d=$config['db'];
    try{
        $pdo=new PDO(
            "mysql:host={$d['host']};port={$d['port']};dbname={$d['name']};charset={$d['charset']}",
            $d['user'],$d['pass'],
            [PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]
        );
        $pdo->exec("SET SESSION sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'");
        return $pdo;
    }catch(Throwable $e){
        error_log('NEXA DB connection failed: '.$e->getMessage());
        throw new RuntimeException('Koneksi database produksi gagal. Aplikasi dihentikan agar tidak menampilkan data demo sebagai data nyata.',0,$e);
    }
}
function storagePath(): string { return __DIR__.'/../storage/demo-data.json'; }
function auditPath(): string { return __DIR__.'/../storage/audit.log'; }
function demoSeed(): array {
    $companies=[
      ['id'=>1,'code'=>'HTL','name'=>'PT Hotel Nusantara','type'=>'Hotel','color'=>'violet'],
      ['id'=>2,'code'=>'RTL','name'=>'CV Retail Sejahtera','type'=>'Retail','color'=>'blue'],
      ['id'=>3,'code'=>'KOS','name'=>'Properti Harmoni','type'=>'Kos & Properti','color'=>'teal'],
      ['id'=>4,'code'=>'FNB','name'=>'PT Kuliner Bersama','type'=>'F&B','color'=>'amber'],
    ];
    $accounts=[
      ['id'=>1,'code'=>'1101','name'=>'Kas & Bank','type'=>'asset','cash'=>1],['id'=>2,'code'=>'1102','name'=>'Piutang Usaha','type'=>'asset','cash'=>0],
      ['id'=>3,'code'=>'1201','name'=>'Aset Tetap','type'=>'asset','cash'=>0],['id'=>4,'code'=>'2101','name'=>'Hutang Usaha','type'=>'liability','cash'=>0],
      ['id'=>5,'code'=>'3101','name'=>'Modal & Saldo Laba','type'=>'equity','cash'=>0],['id'=>6,'code'=>'4101','name'=>'Pendapatan Usaha','type'=>'revenue','cash'=>0],
      ['id'=>7,'code'=>'5101','name'=>'Beban Operasional','type'=>'expense','cash'=>0],['id'=>8,'code'=>'5201','name'=>'Beban Utilitas','type'=>'expense','cash'=>0],
      ['id'=>9,'code'=>'1301','name'=>'Piutang Antar Perusahaan','type'=>'asset','cash'=>0],['id'=>10,'code'=>'2301','name'=>'Hutang Antar Perusahaan','type'=>'liability','cash'=>0],
      ['id'=>11,'code'=>'1191','name'=>'Akumulasi Penyusutan','type'=>'asset','cash'=>0],['id'=>12,'code'=>'5301','name'=>'Beban Penyusutan','type'=>'expense','cash'=>0],
      ['id'=>13,'code'=>'2111','name'=>'PPN Keluaran','type'=>'liability','cash'=>0],['id'=>14,'code'=>'1151','name'=>'PPN Masukan','type'=>'asset','cash'=>0],['id'=>15,'code'=>'7101','name'=>'Laba/Rugi Selisih Kurs','type'=>'revenue','cash'=>0],['id'=>16,'code'=>'5401','name'=>'Laba/Rugi Pelepasan & Penurunan Nilai Aset','type'=>'expense','cash'=>0],
    ];
    $entries=[]; $id=1;
    $tx=[
      [1,'2026-09-24','Pendapatan kamar & layanan',48500000,1,6,null],[2,'2026-09-24','Penjualan toko',31750000,1,6,null],[4,'2026-09-23','Pembelian bahan baku',12450000,7,1,null],[3,'2026-09-23','Penerimaan sewa kos',18600000,1,6,null],[1,'2026-09-22','Pembayaran listrik',9200000,8,1,null],
      [1,'2026-09-21','Pendapatan OTA & walk-in',42600000,1,6,null],[2,'2026-09-21','Penjualan retail',28400000,1,6,null],[3,'2026-09-20','Biaya perawatan properti',5600000,7,1,null],[4,'2026-09-20','Pendapatan restoran',22400000,1,6,null],
      [1,'2026-09-19','Pinjaman antar perusahaan ke Retail',100000000,9,1,2],[2,'2026-09-19','Terima pinjaman dari Hotel',100000000,1,10,1],
    ];
    foreach($tx as $t){ [$co,$dt,$desc,$amt,$debit,$credit,$ic]=$t; $entries[]=['id'=>$id,'no'=>'JRN-202609-'.str_pad((string)$id,4,'0',STR_PAD_LEFT),'company_id'=>$co,'date'=>$dt,'description'=>$desc,'status'=>'posted','source'=>'demo','intercompany_company_id'=>$ic,'lines'=>[['account_id'=>$debit,'debit'=>$amt,'credit'=>0],['account_id'=>$credit,'debit'=>0,'credit'=>$amt]]]; $id++; }
    $branches=[
      ['id'=>1,'company_id'=>1,'code'=>'HTL-MDO','name'=>'Hotel Manado','timezone'=>'Asia/Makassar','active'=>1],
      ['id'=>2,'company_id'=>2,'code'=>'RTL-MDO','name'=>'Retail Manado','timezone'=>'Asia/Makassar','active'=>1],
      ['id'=>3,'company_id'=>3,'code'=>'KOS-A','name'=>'Kos Harmoni A','timezone'=>'Asia/Makassar','active'=>1],
      ['id'=>4,'company_id'=>4,'code'=>'FNB-MDO','name'=>'Kuliner Manado','timezone'=>'Asia/Makassar','active'=>1],
    ];
    $departments=[
      ['id'=>1,'company_id'=>1,'branch_id'=>1,'code'=>'ROOM','name'=>'Rooms','cost_center_code'=>'CC-ROOM','profit_center_code'=>'PC-ROOM','active'=>1],
      ['id'=>2,'company_id'=>1,'branch_id'=>1,'code'=>'FNB','name'=>'Food & Beverage','cost_center_code'=>'CC-FNB','profit_center_code'=>'PC-FNB','active'=>1],
      ['id'=>3,'company_id'=>2,'branch_id'=>2,'code'=>'SALES','name'=>'Sales','cost_center_code'=>'CC-SALES','profit_center_code'=>'PC-SALES','active'=>1],
      ['id'=>4,'company_id'=>3,'branch_id'=>3,'code'=>'RENT','name'=>'Rental','cost_center_code'=>'CC-RENT','profit_center_code'=>'PC-RENT','active'=>1],
    ];
    return ['companies'=>$companies,'branches'=>$branches,'departments'=>$departments,'accounts'=>$accounts,'entries'=>$entries,
      'budgets'=>[['company_id'=>1,'budget'=>1400000000,'actual'=>1285000000],['company_id'=>2,'budget'=>1000000000,'actual'=>940000000],['company_id'=>3,'budget'=>390000000,'actual'=>420000000],['company_id'=>4,'budget'=>560000000,'actual'=>515000000]],
      'assets'=>[['id'=>1,'company_id'=>1,'name'=>'Gedung Hotel Utama','category'=>'Bangunan','cost'=>7800000000,'book'=>6420000000],['id'=>2,'company_id'=>2,'name'=>'Ruko Retail A','category'=>'Bangunan','cost'=>2600000000,'book'=>2380000000],['id'=>3,'company_id'=>3,'name'=>'Kompleks Kos Harmoni','category'=>'Bangunan','cost'=>7400000000,'book'=>7010000000],['id'=>4,'company_id'=>4,'name'=>'Kendaraan Operasional','category'=>'Kendaraan','cost'=>620000000,'book'=>428000000]],
      'trend'=>[['m'=>'Apr','revenue'=>2490,'expense'=>1740],['m'=>'Mei','revenue'=>2620,'expense'=>1795],['m'=>'Jun','revenue'=>2715,'expense'=>1840],['m'=>'Jul','revenue'=>2860,'expense'=>1902],['m'=>'Agu','revenue'=>3015,'expense'=>1968],['m'=>'Sep','revenue'=>3160,'expense'=>2032]],
      'cashflow'=>[['m'=>'Apr','operating'=>540,'investing'=>-110,'financing'=>40],['m'=>'Mei','operating'=>612,'investing'=>-80,'financing'=>-30],['m'=>'Jun','operating'=>655,'investing'=>-140,'financing'=>20],['m'=>'Jul','operating'=>702,'investing'=>-105,'financing'=>-10],['m'=>'Agu','operating'=>748,'investing'=>-90,'financing'=>-35],['m'=>'Sep','operating'=>812,'investing'=>-120,'financing'=>15]],
      'users'=>[
        ['id'=>1,'name'=>'Group Owner','email'=>'owner@nexa.local','role'=>'group_owner','active'=>1],
        ['id'=>2,'name'=>'Finance Controller','email'=>'finance@nexa.local','role'=>'group_finance','active'=>1],
        ['id'=>3,'name'=>'Entity Admin Hotel','email'=>'hotel@nexa.local','role'=>'entity_admin','company_id'=>1,'active'=>1],
        ['id'=>4,'name'=>'Internal Auditor','email'=>'audit@nexa.local','role'=>'auditor','active'=>1],
      ],
      'periods'=>[
        ['id'=>1,'year'=>2026,'month'=>8,'status'=>'closed','closed_at'=>'2026-09-05 18:00:00','closed_by'=>2],
        ['id'=>2,'year'=>2026,'month'=>9,'status'=>'open','closed_at'=>null,'closed_by'=>null],
      ],
      'approvals'=>[
        ['id'=>1,'journal_id'=>null,'company_id'=>1,'date'=>'2026-09-24','description'=>'CAPEX renovasi kamar tahap 1','amount'=>78000000,'requested_by'=>3,'status'=>'pending','requested_at'=>'2026-09-24 11:20:00'],
        ['id'=>2,'journal_id'=>null,'company_id'=>2,'date'=>'2026-09-23','description'=>'Pembelian stok elektronik volume besar','amount'=>46500000,'requested_by'=>2,'status'=>'approved','requested_at'=>'2026-09-23 09:10:00','decided_at'=>'2026-09-23 09:42:00','decided_by'=>1],
      ],
      'invoices'=>[
        ['id'=>1,'company_id'=>1,'type'=>'receivable','number'=>'AR-HTL-260901','party'=>'OTA Nusantara','issue_date'=>'2026-09-05','due_date'=>'2026-10-05','amount'=>42500000,'paid'=>17500000,'status'=>'partial'],
        ['id'=>2,'company_id'=>3,'type'=>'receivable','number'=>'AR-KOS-260917','party'=>'Tenant Korporat A','issue_date'=>'2026-09-17','due_date'=>'2026-09-30','amount'=>18000000,'paid'=>0,'status'=>'open'],
        ['id'=>3,'company_id'=>4,'type'=>'payable','number'=>'AP-FNB-260920','party'=>'Supplier Bahan Pangan','issue_date'=>'2026-09-20','due_date'=>'2026-10-04','amount'=>28750000,'paid'=>10000000,'status'=>'partial'],
        ['id'=>4,'company_id'=>2,'type'=>'payable','number'=>'AP-RTL-260925','party'=>'Distributor Elektronik','issue_date'=>'2026-09-25','due_date'=>'2026-10-25','amount'=>53200000,'paid'=>0,'status'=>'open'],
      ],
      'bank_feed'=>[
        ['id'=>1,'company_id'=>1,'date'=>'2026-09-24','description'=>'SETTLEMENT OTA 240926','amount'=>48500000,'direction'=>'in','status'=>'matched','journal_id'=>1],
        ['id'=>2,'company_id'=>1,'date'=>'2026-09-22','description'=>'PLN HOTEL SEPTEMBER','amount'=>9200000,'direction'=>'out','status'=>'matched','journal_id'=>5],
        ['id'=>3,'company_id'=>2,'date'=>'2026-09-25','description'=>'TRANSFER MASUK ECOMMERCE','amount'=>14750000,'direction'=>'in','status'=>'unmatched','journal_id'=>null],
        ['id'=>4,'company_id'=>4,'date'=>'2026-09-25','description'=>'DEBIT SUPPLIER 8921','amount'=>6350000,'direction'=>'out','status'=>'unmatched','journal_id'=>null],
      ],
      'currencies'=>[
        ['code'=>'IDR','name'=>'Indonesian Rupiah','rate'=>1,'updated_at'=>'2026-09-25'],
        ['code'=>'USD','name'=>'US Dollar','rate'=>16850,'updated_at'=>'2026-09-25'],
        ['code'=>'SGD','name'=>'Singapore Dollar','rate'=>13120,'updated_at'=>'2026-09-25'],
      ],
      'tax_profiles'=>[
        ['id'=>1,'code'=>'PPN11','name'=>'PPN Keluaran','rate'=>11.0,'type'=>'output','input_account_id'=>14,'output_account_id'=>13,'active'=>1],
        ['id'=>2,'code'=>'PPNIN11','name'=>'PPN Masukan','rate'=>11.0,'type'=>'input','input_account_id'=>14,'output_account_id'=>13,'active'=>1],
        ['id'=>3,'code'=>'NONE','name'=>'Non Pajak','rate'=>0.0,'type'=>'none','input_account_id'=>null,'output_account_id'=>null,'active'=>1],
      ],
      'payments'=>[],
      'parties'=>[
        ['id'=>1,'company_id'=>1,'party_type'=>'customer','code'=>'OTA-NUS','name'=>'OTA Nusantara','currency'=>'IDR','active'=>1],
        ['id'=>2,'company_id'=>4,'party_type'=>'vendor','code'=>'SUP-FNB','name'=>'Supplier Bahan Pangan','currency'=>'IDR','active'=>1],
      ],
      'invoice_lines'=>[],
      'payment_allocations'=>[],
      'tax_transactions'=>[],
      'asset_depreciation_schedule'=>[],
      'reconciliation_sessions'=>[],
      'consolidation_runs'=>[],
      'elimination_entries'=>[],
      'approval_decisions'=>[],
      'fx_rates'=>[],
      'fx_revaluation_runs'=>[],
      'integration_outbox'=>[],
      'period_close_tasks'=>[],
      'asset_events'=>[],
      'settlement_batches'=>[],
      'bank_import_profiles'=>[],
      'bank_statement_imports'=>[],
      'approval_policies'=>[],
      'invoice_adjustments'=>[],
      'bank_accounts'=>[
        ['id'=>1,'company_id'=>1,'account_id'=>1,'bank_name'=>'Bank Utama','account_name'=>'PT Hotel Nusantara','account_number'=>'****1001','active'=>1],
        ['id'=>2,'company_id'=>2,'account_id'=>1,'bank_name'=>'Bank Utama','account_name'=>'CV Retail Sejahtera','account_number'=>'****2001','active'=>1],
      ],
      'income_categories'=>[
        ['id'=>1,'company_id'=>1,'code'=>'ROOM','name'=>'Pendapatan Kamar','revenue_account_id'=>6,'active'=>1,'sort_order'=>10],
        ['id'=>2,'company_id'=>1,'code'=>'FNB','name'=>'Restoran & Mini Bar','revenue_account_id'=>6,'active'=>1,'sort_order'=>20],
        ['id'=>3,'company_id'=>1,'code'=>'LAUNDRY','name'=>'Laundry','revenue_account_id'=>6,'active'=>1,'sort_order'=>30],
        ['id'=>4,'company_id'=>1,'code'=>'OTHER','name'=>'Pendapatan Lain','revenue_account_id'=>6,'active'=>1,'sort_order'=>90],
        ['id'=>5,'company_id'=>2,'code'=>'SALES','name'=>'Penjualan Barang','revenue_account_id'=>6,'active'=>1,'sort_order'=>10],
        ['id'=>6,'company_id'=>2,'code'=>'SERVICE','name'=>'Jasa & Layanan','revenue_account_id'=>6,'active'=>1,'sort_order'=>20],
        ['id'=>7,'company_id'=>3,'code'=>'RENT','name'=>'Sewa Kamar / Unit','revenue_account_id'=>6,'active'=>1,'sort_order'=>10],
        ['id'=>8,'company_id'=>3,'code'=>'UTILITY','name'=>'Listrik / Air / Service','revenue_account_id'=>6,'active'=>1,'sort_order'=>20],
        ['id'=>9,'company_id'=>4,'code'=>'DINEIN','name'=>'Dine-in','revenue_account_id'=>6,'active'=>1,'sort_order'=>10],
        ['id'=>10,'company_id'=>4,'code'=>'TAKEAWAY','name'=>'Takeaway / Delivery','revenue_account_id'=>6,'active'=>1,'sort_order'=>20],
        ['id'=>11,'company_id'=>4,'code'=>'EVENT','name'=>'Catering / Event','revenue_account_id'=>6,'active'=>1,'sort_order'=>30],
      ],
      'expense_categories'=>[
        ['id'=>1,'company_id'=>1,'code'=>'UTILITY','name'=>'Listrik / Air / Utilitas','expense_account_id'=>8,'tax_profile_id'=>2,'active'=>1],
        ['id'=>2,'company_id'=>1,'code'=>'OPS','name'=>'Operasional Hotel','expense_account_id'=>7,'tax_profile_id'=>2,'active'=>1],
        ['id'=>3,'company_id'=>2,'code'=>'OPS','name'=>'Operasional Retail','expense_account_id'=>7,'tax_profile_id'=>2,'active'=>1],
        ['id'=>4,'company_id'=>3,'code'=>'MAINT','name'=>'Maintenance Properti','expense_account_id'=>7,'tax_profile_id'=>2,'active'=>1],
        ['id'=>5,'company_id'=>4,'code'=>'SUPPLY','name'=>'Bahan & Operasional F&B','expense_account_id'=>7,'tax_profile_id'=>2,'active'=>1],
      ],
      'bank_transfers'=>[],
      'opening_balance_batches'=>[],
      'recurring_journal_templates'=>[],
      'recurring_journal_runs'=>[],
      'cash_forecast_items'=>[
        ['id'=>1,'company_id'=>1,'branch_id'=>1,'forecast_date'=>'2026-10-05','direction'=>'inflow','source_type'=>'manual','description'=>'Settlement OTA Oktober','amount'=>65000000,'currency'=>'IDR','probability_pct'=>90,'status'=>'planned'],
        ['id'=>2,'company_id'=>1,'branch_id'=>1,'forecast_date'=>'2026-10-10','direction'=>'outflow','source_type'=>'manual','description'=>'Payroll & utilitas hotel','amount'=>42000000,'currency'=>'IDR','probability_pct'=>100,'status'=>'planned'],
      ],
      'year_end_closes'=>[],
      'onboarding_import_jobs'=>[],'onboarding_import_errors'=>[],'ap_payment_batches'=>[],'ap_payment_batch_lines'=>[],'document_attachments'=>[],
      'employee_advances'=>[],'employee_advance_settlements'=>[],'loan_facilities'=>[],'loan_payments'=>[],'equity_transactions'=>[],'budget_scenarios'=>[],'budget_scenario_lines'=>[],
      'eliminations'=>[],
      'fx_events'=>[],
      'integration_staging'=>[
        ['id'=>1,'source'=>'HOTEL-PMS','company_id'=>1,'external_ref'=>'HTL-SETTLE-240926','status'=>'validated','amount'=>48500000,'received_at'=>'2026-09-24 22:11:00'],
        ['id'=>2,'source'=>'POS-RETAIL','company_id'=>2,'external_ref'=>'POS-DAY-240926','status'=>'posted','amount'=>31750000,'received_at'=>'2026-09-24 23:10:00'],
      ],
      'meta'=>['next_entry_id'=>$id,'next_approval_id'=>3,'next_payment_id'=>1,'next_elimination_id'=>1,'next_bank_id'=>5,'next_bank_account_id'=>3,'next_company_id'=>5,'next_user_id'=>5,'next_asset_id'=>5,'next_income_category_id'=>12,'next_account_id'=>17,'next_party_id'=>3,'next_expense_category_id'=>6,'next_bank_transfer_id'=>1,'next_opening_balance_id'=>1,'next_recurring_id'=>1,'next_recurring_run_id'=>1,'next_cash_forecast_id'=>3,'next_year_end_id'=>1,'next_import_job_id'=>1,'next_import_error_id'=>1,'next_payment_batch_id'=>1,'next_payment_batch_line_id'=>1,'next_document_id'=>1,'next_advance_id'=>1,'next_advance_settlement_id'=>1,'next_loan_id'=>1,'next_loan_payment_id'=>1,'next_equity_tx_id'=>1,'next_budget_scenario_id'=>1,'next_budget_scenario_line_id'=>1,'next_invoice_line_id'=>1,'next_payment_allocation_id'=>1,'next_tax_transaction_id'=>1,'next_dep_schedule_id'=>1,'next_reconciliation_session_id'=>1,'next_consolidation_run_id'=>1,'next_elimination_entry_id'=>1,'next_approval_decision_id'=>1,'next_fx_rate_id'=>1,'next_fx_revaluation_id'=>1,'next_outbox_id'=>1,'version'=>6,'approval_threshold'=>25000000]
    ];
}
function loadStore(): array { global $config; if(!$config['demo_mode']) return loadDbStore(); $p=storagePath(); if(!is_file($p)){ $d=demoSeed(); @file_put_contents($p,json_encode($d,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX); return $d; } $d=json_decode((string)file_get_contents($p),true); if(!is_array($d))$d=demoSeed(); $seed=demoSeed(); foreach(['branches','departments','users','periods','approvals','invoices','bank_feed','bank_accounts','income_categories','currencies','tax_profiles','payments','eliminations','fx_events','integration_staging','parties','invoice_lines','payment_allocations','tax_transactions','asset_depreciation_schedule','reconciliation_sessions','consolidation_runs','elimination_entries','approval_decisions','fx_rates','fx_revaluation_runs','integration_outbox','period_close_tasks','asset_events','settlement_batches','bank_import_profiles','bank_statement_imports','approval_policies','invoice_adjustments','expense_categories','bank_transfers','opening_balance_batches','recurring_journal_templates','recurring_journal_runs','cash_forecast_items','year_end_closes','onboarding_import_jobs','onboarding_import_errors','ap_payment_batches','ap_payment_batch_lines','document_attachments','employee_advances','employee_advance_settlements','loan_facilities','loan_payments','equity_transactions','budget_scenarios','budget_scenario_lines'] as $k) if(!isset($d[$k]))$d[$k]=$seed[$k]; $d['meta']=array_merge($seed['meta'],$d['meta']??[]); return $d; }
function saveStore(array $d): void { $tmp=storagePath().'.tmp'; file_put_contents($tmp,json_encode($d,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX); rename($tmp,storagePath()); }
function loadDbStore(): array {
    $pdo=db();
    if(!$pdo) throw new RuntimeException('Database produksi tidak tersedia.');
    $companies=$pdo->query("SELECT id,code,name,business_type type,'violet' color FROM companies WHERE is_active=1 ORDER BY id")->fetchAll();
    $branches=$pdo->query("SELECT id,company_id,code,name,timezone,is_active active FROM branches WHERE is_active=1 ORDER BY company_id,code")->fetchAll();
    $departments=$pdo->query("SELECT id,company_id,branch_id,code,name,cost_center_code,profit_center_code,is_active active FROM departments WHERE is_active=1 ORDER BY company_id,branch_id,code")->fetchAll();
    $accounts=$pdo->query("SELECT id,company_id,code,name,account_type type,is_cash_bank cash FROM chart_accounts WHERE is_active=1 ORDER BY company_id,code")->fetchAll();
    $rows=$pdo->query("SELECT je.id,je.journal_no no,je.company_id,je.branch_id,je.department_id,je.journal_date date,je.description,je.status,je.source_type source,je.reversal_of,je.reversed_by,jl.account_id,jl.branch_id line_branch_id,jl.department_id line_department_id,jl.debit,jl.credit,jl.cost_center,jl.profit_center,jl.project_code,jl.transaction_currency,jl.foreign_amount,jl.exchange_rate,jl.base_amount,jl.intercompany_company_id FROM journal_entries je JOIN journal_lines jl ON jl.journal_id=je.id WHERE je.status='posted' ORDER BY je.journal_date,je.id,jl.id")->fetchAll();
    $entries=[];
    foreach($rows as $r){
        $id=(int)$r['id'];
        if(!isset($entries[$id])) $entries[$id]=['id'=>$id,'no'=>$r['no'],'company_id'=>(int)$r['company_id'],'branch_id'=>$r['branch_id']?(int)$r['branch_id']:null,'department_id'=>$r['department_id']?(int)$r['department_id']:null,'date'=>$r['date'],'description'=>$r['description'],'status'=>$r['status'],'source'=>$r['source'],'reversal_of'=>$r['reversal_of']?(int)$r['reversal_of']:null,'reversed_by'=>$r['reversed_by']?(int)$r['reversed_by']:null,'intercompany_company_id'=>$r['intercompany_company_id']?(int)$r['intercompany_company_id']:null,'lines'=>[]];
        $entries[$id]['lines'][]=['account_id'=>(int)$r['account_id'],'branch_id'=>$r['line_branch_id']?(int)$r['line_branch_id']:null,'department_id'=>$r['line_department_id']?(int)$r['line_department_id']:null,'debit'=>(float)$r['debit'],'credit'=>(float)$r['credit'],'cost_center'=>$r['cost_center'],'profit_center'=>$r['profit_center'],'project_code'=>$r['project_code'],'transaction_currency'=>$r['transaction_currency']??'IDR','foreign_amount'=>$r['foreign_amount']!==null?(float)$r['foreign_amount']:null,'exchange_rate'=>(float)($r['exchange_rate']??1),'base_amount'=>$r['base_amount']!==null?(float)$r['base_amount']:max((float)$r['debit'],(float)$r['credit'])];
    }
    $users=$pdo->query("SELECT id,name,email,role,company_id,is_active active FROM users WHERE is_active=1 ORDER BY id")->fetchAll();
    $periods=$pdo->query("SELECT id,company_id,fiscal_year year,period month,status,closed_at,closed_by FROM fiscal_periods ORDER BY fiscal_year DESC,period DESC,company_id")->fetchAll();
    $approvals=$pdo->query("SELECT id,journal_id,company_id,journal_date date,description,amount,requested_by,status,requested_at,decided_at,decided_by,payload_json FROM journal_approvals ORDER BY requested_at DESC")->fetchAll();
    foreach($approvals as &$a){$a['payload']=$a['payload_json']?json_decode((string)$a['payload_json'],true):null;unset($a['payload_json']);}unset($a);
    $invoices=$pdo->query("SELECT id,company_id,branch_id,department_id,party_id,invoice_type type,invoice_no number,party_name party,issue_date,due_date,subtotal,tax_total,amount,paid_amount paid,status,currency,journal_id,notes FROM invoices WHERE status<>'void' ORDER BY due_date")->fetchAll();
    $bankFeed=$pdo->query("SELECT id,company_id,txn_date date,description,amount,direction,status,journal_id,external_ref FROM bank_feed WHERE status<>'ignored' ORDER BY txn_date DESC,id DESC")->fetchAll();
    $bankAccounts=$pdo->query("SELECT id,company_id,account_id,bank_name,account_name,account_number,is_active active FROM bank_accounts WHERE is_active=1 ORDER BY company_id,id")->fetchAll();
    $currencies=$pdo->query("SELECT cr.currency_code code,cr.currency_code name,cr.rate_to_idr rate,cr.rate_date updated_at FROM currency_rates cr JOIN (SELECT currency_code,MAX(rate_date) max_date FROM currency_rates GROUP BY currency_code) x ON x.currency_code=cr.currency_code AND x.max_date=cr.rate_date ORDER BY cr.currency_code")->fetchAll();
    if(!$currencies)$currencies=[['code'=>'IDR','name'=>'Indonesian Rupiah','rate'=>1,'updated_at'=>date('Y-m-d')]];
    $budgets=$pdo->query("SELECT id,company_id,branch_id,department_id,fiscal_year,period,account_id,amount budget,scenario FROM budgets WHERE scenario='budget' ORDER BY fiscal_year,period,company_id,account_id")->fetchAll();
    $assets=$pdo->query("SELECT id,company_id,branch_id,department_id,asset_code,name,category,acquisition_date,acquisition_cost cost,useful_life_months,residual_value,asset_account_id,accumulated_depreciation_account_id,depreciation_expense_account_id,acquisition_journal_id,status,GREATEST(residual_value,acquisition_cost-(SELECT COALESCE(SUM(depreciation_amount),0) FROM asset_depreciation_schedule ads WHERE ads.asset_id=fixed_assets.id AND ads.status='posted')) book FROM fixed_assets WHERE status='active' ORDER BY id")->fetchAll();
    $taxProfiles=$pdo->query("SELECT id,code,name,rate,tax_type type,input_account_id,output_account_id,is_active active FROM tax_profiles ORDER BY id")->fetchAll();
    $payments=$pdo->query("SELECT id,invoice_id,company_id,payment_date date,amount,method,reference_no reference,journal_id FROM invoice_payments ORDER BY payment_date DESC,id DESC")->fetchAll();
    $eliminations=$pdo->query("SELECT id,period_key period,from_company_id,to_company_id,amount,description,status,created_at FROM intercompany_eliminations ORDER BY created_at DESC")->fetchAll();
    $fxEvents=$pdo->query("SELECT id,company_id,event_date date,currency,foreign_amount,book_rate,settlement_rate,base_amount,gain_loss,description FROM fx_events ORDER BY event_date DESC,id DESC")->fetchAll();
    $staging=$pdo->query("SELECT id,source,company_id,external_ref,status,amount,received_at FROM integration_staging ORDER BY received_at DESC")->fetchAll();
    $parties=$pdo->query("SELECT id,company_id,party_type,code,name,tax_id,email,phone,address_text,currency,ar_account_id,ap_account_id,is_active active FROM parties WHERE is_active=1 ORDER BY company_id,name")->fetchAll();
    $invoiceLines=$pdo->query("SELECT id,invoice_id,account_id,description,quantity,unit_price,tax_profile_id,tax_amount,line_total FROM invoice_lines ORDER BY invoice_id,id")->fetchAll();
    $allocations=$pdo->query("SELECT id,payment_id,invoice_id,allocated_amount,created_at FROM payment_allocations ORDER BY id DESC")->fetchAll();
    $taxTransactions=$pdo->query("SELECT id,company_id,tax_profile_id,journal_id,transaction_date,filing_period,tax_base,tax_amount,direction,external_ref,status FROM tax_transactions ORDER BY transaction_date DESC,id DESC")->fetchAll();
    $depSchedule=$pdo->query("SELECT id,asset_id,period,depreciation_amount,accumulated_amount,book_value,journal_id,status FROM asset_depreciation_schedule ORDER BY period DESC,asset_id")->fetchAll();
    $reconSessions=$pdo->query("SELECT id,company_id,bank_account_id,period_start,period_end,opening_balance,closing_balance,matched_amount,difference_amount,status,closed_at,reopened_at FROM bank_reconciliation_sessions ORDER BY period_end DESC,id DESC")->fetchAll();
    $consolidationRuns=$pdo->query("SELECT id,period,run_no,status,entity_count,elimination_count,created_at,posted_at,locked_at FROM consolidation_runs ORDER BY period DESC,id DESC")->fetchAll();
    $eliminationEntries=$pdo->query("SELECT id,consolidation_run_id,from_company_id,to_company_id,account_id,branch_id,department_id,debit,credit,reference,description FROM elimination_entries ORDER BY consolidation_run_id,id")->fetchAll();
    $fxRates=$pdo->query("SELECT id,rate_date,base_currency,quote_currency,rate,source FROM fx_rates ORDER BY rate_date DESC,id DESC")->fetchAll();
    $fxRevals=$pdo->query("SELECT id,company_id,period,currency,closing_rate,gain_loss_amount,journal_id,status FROM fx_revaluation_runs ORDER BY period DESC,id DESC")->fetchAll();
    $outbox=$pdo->query("SELECT id,company_id,event_type,aggregate_type,aggregate_id,status,attempts,available_at,sent_at,last_error FROM integration_outbox ORDER BY id DESC LIMIT 100")->fetchAll();
    $closeTasks=$pdo->query("SELECT id,company_id,fiscal_year year,period month,task_code,task_name,status,detail_text,completed_at FROM period_close_tasks ORDER BY fiscal_year DESC,period DESC,company_id,task_code")->fetchAll();
    $incomeCategories=$pdo->query("SELECT id,company_id,code,name,revenue_account_id,is_active active,sort_order FROM income_categories WHERE is_active=1 ORDER BY company_id,sort_order,id")->fetchAll();
    return ['companies'=>$companies,'branches'=>$branches,'departments'=>$departments,'accounts'=>$accounts,'entries'=>array_values($entries),'budgets'=>$budgets,'assets'=>$assets,'trend'=>[],'cashflow'=>[],'users'=>$users,'demo_users'=>[],'periods'=>$periods,'approvals'=>$approvals,'invoices'=>$invoices,'invoice_lines'=>$invoiceLines,'payment_allocations'=>$allocations,'parties'=>$parties,'bank_feed'=>$bankFeed,'bank_accounts'=>$bankAccounts,'income_categories'=>$incomeCategories,'currencies'=>$currencies,'tax_profiles'=>$taxProfiles,'tax_transactions'=>$taxTransactions,'payments'=>$payments,'eliminations'=>$eliminations,'fx_events'=>$fxEvents,'fx_rates'=>$fxRates,'fx_revaluation_runs'=>$fxRevals,'integration_staging'=>$staging,'integration_outbox'=>$outbox,'asset_depreciation_schedule'=>$depSchedule,'reconciliation_sessions'=>$reconSessions,'consolidation_runs'=>$consolidationRuns,'elimination_entries'=>$eliminationEntries,'period_close_tasks'=>$closeTasks,'meta'=>['approval_threshold'=>(float)($GLOBALS['config']['approval_threshold']??25000000)]];
}
function companyMap(array $s): array { $m=[]; foreach($s['companies'] as $c)$m[(int)$c['id']]=$c; return $m; }
function accountMap(array $s): array { $m=[]; foreach($s['accounts'] as $a)$m[(int)$a['id']]=$a; return $m; }
function entryBalanced(array $lines): bool { return (new \Nexa\Legacy\EnterpriseFacade())->entryBalanced($lines); }
function accountNormal(string $type): string { return in_array($type,['asset','expense'],true)?'debit':'credit'; }
function lineEffect(array $account, array $line): float { return accountNormal($account['type'])==='debit' ? ((float)$line['debit']-(float)$line['credit']) : ((float)$line['credit']-(float)$line['debit']); }
function metrics(array $s, ?int $companyId=null): array { $am=accountMap($s); $revenue=$expense=$cash=$assets=$liabilities=$equity=0.0; $tx=0; foreach($s['entries'] as $e){ if($e['status']!=='posted'||($companyId && (int)$e['company_id']!==$companyId))continue; $tx++; foreach($e['lines'] as $l){ $a=$am[(int)$l['account_id']]??null; if(!$a)continue; $eff=lineEffect($a,$l); if($a['type']==='revenue'){if(($e['source']??'')!=='year_end_close')$revenue+=$eff;} elseif($a['type']==='expense'){if(($e['source']??'')!=='year_end_close')$expense+=$eff;} elseif($a['type']==='asset')$assets+=$eff; elseif($a['type']==='liability')$liabilities+=$eff; elseif($a['type']==='equity')$equity+=$eff; if(!empty($a['cash']))$cash+=$eff; } } return compact('revenue','expense','cash','assets','liabilities','equity','tx')+['profit'=>$revenue-$expense,'margin'=>$revenue>0?($revenue-$expense)/$revenue*100:0]; }
function companyMetrics(array $s): array { $out=[]; foreach($s['companies'] as $c){ $m=metrics($s,(int)$c['id']); $out[]=array_merge($c,$m); } return $out; }
function transactions(array $s, int $limit=50): array { $cm=companyMap($s);$am=accountMap($s);$out=[]; $entries=array_reverse($s['entries']); foreach($entries as $e){ if($e['status']!=='posted')continue; $amount=0;$type='journal';$account='Jurnal Umum'; foreach($e['lines'] as $l){$a=$am[(int)$l['account_id']]??null;if(!$a)continue;if((float)$l['debit']>0)$amount=max($amount,(float)$l['debit']); if($a['type']==='revenue'&&$l['credit']>0){$type='income';$account=$a['name'];} if($a['type']==='expense'&&$l['debit']>0){$type='expense';$account=$a['name'];}} $out[]=['id'=>$e['id'],'no'=>$e['no'],'date'=>$e['date'],'company'=>$cm[(int)$e['company_id']]['name']??'-','desc'=>$e['description'],'account'=>$account,'amount'=>$amount,'type'=>$type,'status'=>ucfirst($e['status'])]; if(count($out)>=$limit)break;} return $out; }
function intercompanySummary(array $s): array { $cm=companyMap($s);$out=[]; foreach($s['entries'] as $e){$to=$e['intercompany_company_id']??null;if(!$to)continue;$amt=0;foreach($e['lines'] as $l)$amt=max($amt,(float)$l['debit'],(float)$l['credit']);$out[]=['date'=>$e['date'],'from'=>$cm[(int)$e['company_id']]['name']??'-','to'=>$cm[(int)$to]['name']??'-','description'=>$e['description'],'amount'=>$amt,'status'=>'Matched'];} return $out; }
function monthKeys(int $months=6, ?string $endKey=null): array {
    $months=max(1,min(24,$months));
    $end=$endKey && preg_match('/^\d{4}-\d{2}$/',$endKey)?DateTimeImmutable::createFromFormat('!Y-m',$endKey):new DateTimeImmutable('first day of this month');
    $out=[];for($i=$months-1;$i>=0;$i--)$out[]=$end->modify("-$i months")->format('Y-m');return $out;
}
function monthLabel(string $key): string { $map=['01'=>'Jan','02'=>'Feb','03'=>'Mar','04'=>'Apr','05'=>'Mei','06'=>'Jun','07'=>'Jul','08'=>'Agu','09'=>'Sep','10'=>'Okt','11'=>'Nov','12'=>'Des'];return ($map[substr($key,5,2)]??substr($key,5,2)).' '.substr($key,0,4); }
function metricsForPeriod(array $s,string $period,?int $companyId=null): array { $copy=$s;$copy['entries']=array_values(array_filter($s['entries']??[],fn($e)=>str_starts_with((string)$e['date'],$period)&&(!$companyId||(int)$e['company_id']===$companyId)));return metrics($copy,$companyId); }
function dashboardMetrics(array $s,string $period): array { $all=metrics($s);$p=metricsForPeriod($s,$period);foreach(['cash','assets','liabilities','equity'] as $k)$p[$k]=$all[$k];return $p; }
function companyMetricsForPeriod(array $s,string $period): array { $out=[];foreach($s['companies'] as $c){$all=metrics($s,(int)$c['id']);$p=metricsForPeriod($s,$period,(int)$c['id']);foreach(['cash','assets','liabilities','equity'] as $k)$p[$k]=$all[$k];$out[]=array_merge($c,$p);}return $out; }
function ledgerTrend(array $s,int $months=6,string $endKey=''): array { $keys=monthKeys($months,$endKey?:date('Y-m'));$out=[];foreach($keys as $k){$m=metricsForPeriod($s,$k);$out[]=['m'=>monthLabel($k),'revenue'=>round($m['revenue']/1000000,2),'expense'=>round($m['expense']/1000000,2)];}return $out; }
function cashflowTrend(array $s,int $months=6,string $endKey=''): array { $keys=monthKeys($months,$endKey?:date('Y-m'));$acc=accountMap($s);$rows=[];foreach($keys as $k)$rows[$k]=['m'=>monthLabel($k),'operating'=>0.0,'investing'=>0.0,'financing'=>0.0];foreach($s['entries']??[] as $e){$k=substr((string)$e['date'],0,7);if(!isset($rows[$k])||($e['status']??'')!=='posted')continue;$cash=0.0;$counterTypes=[];foreach($e['lines'] as $l){$a=$acc[(int)$l['account_id']]??null;if(!$a)continue;if(!empty($a['cash']))$cash+=(float)$l['debit']-(float)$l['credit'];else $counterTypes[]=$a['type'];}if(abs($cash)<0.005)continue;$bucket='operating';if(array_intersect($counterTypes,['equity','liability']))$bucket='financing';elseif(in_array('asset',$counterTypes,true))$bucket='investing';$rows[$k][$bucket]+=$cash/1000000;}return array_values($rows); }
function revenueGrowth(array $s,string $period): float { $curr=metricsForPeriod($s,$period)['revenue'];$prev=(DateTimeImmutable::createFromFormat('!Y-m',$period))->modify('-1 month')->format('Y-m');$old=metricsForPeriod($s,$prev)['revenue'];return $old>0?(($curr-$old)/$old*100):0.0; }
function budgetRowsForPeriod(array $s,string $period): array { [$y,$m]=array_map('intval',explode('-',$period));$rows=[];$am=accountMap($s);foreach($s['budgets']??[] as $b){if(isset($b['fiscal_year'])&&((int)$b['fiscal_year']!==$y||(int)$b['period']!==$m))continue;$cid=(int)$b['company_id'];$budget=(float)($b['budget']??0);if(isset($b['actual']))$actual=(float)$b['actual'];else{$actual=0.0;$aid=(int)($b['account_id']??0);foreach($s['entries']??[] as$e){if((int)$e['company_id']!==$cid||($e['status']??'')!=='posted'||substr((string)$e['date'],0,7)!==$period)continue;if(!empty($b['branch_id'])&&(int)($e['branch_id']??0)!==(int)$b['branch_id'])continue;if(!empty($b['department_id'])&&(int)($e['department_id']??0)!==(int)$b['department_id'])continue;foreach($e['lines']??[] as$l){if($aid&&(int)$l['account_id']!==$aid)continue;$a=$am[(int)$l['account_id']]??null;if(!$a)continue;$actual+=lineEffect($a,$l);}}}$rows[]=['company_id'=>$cid,'branch_id'=>$b['branch_id']??null,'department_id'=>$b['department_id']??null,'account_id'=>$b['account_id']??null,'budget'=>$budget,'actual'=>$actual];}return $rows; }
function validateJournalAccounts(array $s,int $company,int $debit,int $credit): void { $cm=companyMap($s);if(!isset($cm[$company]))throw new InvalidArgumentException('Badan usaha tidak ditemukan.');$am=accountMap($s);foreach([$debit,$credit] as $aid){$a=$am[$aid]??null;if(!$a)throw new InvalidArgumentException('Akun jurnal tidak ditemukan atau tidak aktif.');$owner=(int)($a['company_id']??0);if($owner!==0&&$owner!==$company)throw new RuntimeException('Akun jurnal bukan milik badan usaha yang dipilih.');} }
function accountIdByCode(array $s,int $company,string $code): int { $global=null;foreach($s['accounts']??[] as $a){if((string)$a['code']!==$code)continue;$owner=(int)($a['company_id']??0);if($owner===$company)return (int)$a['id'];if($owner===0)$global=(int)$a['id'];}if($global)return $global;throw new RuntimeException('Akun wajib '.$code.' belum dikonfigurasi untuk badan usaha ini.'); }
function validateIntercompany(array $s,int $company,?int $counterparty): void { if(!$counterparty)return;if($counterparty===$company)throw new InvalidArgumentException('Counterparty intercompany tidak boleh sama dengan badan usaha asal.');$cm=companyMap($s);if(!isset($cm[$counterparty]))throw new InvalidArgumentException('Counterparty intercompany tidak ditemukan.'); }
function normalizeJournalInput(array $input): array { $j=['company'=>(int)($input['company_id']??0),'date'=>(string)($input['date']??date('Y-m-d')),'desc'=>trim((string)($input['description']??'')),'amount'=>(float)($input['amount']??0),'debit'=>(int)($input['debit_account_id']??0),'credit'=>(int)($input['credit_account_id']??0),'ic'=>(($input['intercompany_company_id']??'')!=='')?(int)$input['intercompany_company_id']:null];if(!$j['company']||!$j['desc']||$j['amount']<=0||!$j['debit']||!$j['credit']||$j['debit']===$j['credit'])throw new InvalidArgumentException('Data jurnal belum lengkap atau akun debit/kredit sama.');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$j['date']))throw new InvalidArgumentException('Format tanggal tidak valid.');return $j; }
function lockAndAssertPeriodOpenDb(PDO $pdo,string $date): void { $y=(int)substr($date,0,4);$m=(int)substr($date,5,2);$pdo->prepare("INSERT INTO fiscal_periods(fiscal_year,period,status) VALUES(?,?,'open') ON DUPLICATE KEY UPDATE id=id")->execute([$y,$m]);$st=$pdo->prepare("SELECT status FROM fiscal_periods WHERE fiscal_year=? AND period=? FOR UPDATE");$st->execute([$y,$m]);if(($st->fetchColumn()?:'open')==='closed')throw new RuntimeException('Periode akuntansi '.sprintf('%04d-%02d',$y,$m).' sudah ditutup.'); }
function insertPostedJournalDb(PDO $pdo,array $j,string $source='manual',?int $reversalOf=null): array { $no=($source==='reversal'?'REV':'JRN').'-'.str_replace('-','',substr($j['date'],0,7)).'-'.strtoupper(bin2hex(random_bytes(3)));$st=$pdo->prepare("INSERT INTO journal_entries(company_id,journal_no,journal_date,description,source_type,status,posted_at,created_by,reversal_of) VALUES(?,?,?,?,?,'posted',NOW(),?,?)");$st->execute([$j['company'],$no,$j['date'],$j['desc'],$source,$_SESSION['user_id']??null,$reversalOf]);$jid=(int)$pdo->lastInsertId();$sl=$pdo->prepare("INSERT INTO journal_lines(journal_id,account_id,debit,credit,intercompany_company_id) VALUES(?,?,?,?,?)");$sl->execute([$jid,$j['debit'],$j['amount'],0,$j['ic']]);$sl->execute([$jid,$j['credit'],0,$j['amount'],$j['ic']]);return ['id'=>$jid,'no'=>$no,'status'=>'posted']; }

function dailyIncomeRecent(array $s,int $limit=20): array { $cm=companyMap($s);$out=[];foreach(array_reverse($s['entries']??[]) as $e){if(($e['status']??'')!=='posted'||($e['source']??'')!=='daily_income')continue;$total=0.0;foreach($e['lines']??[] as $l)$total+=(float)($l['debit']??0);$out[]=['id'=>(int)$e['id'],'no'=>$e['no'],'date'=>$e['date'],'company'=>$cm[(int)$e['company_id']]['name']??'-','description'=>$e['description'],'amount'=>$total];if(count($out)>=$limit)break;}return $out; }
function validateMultiJournalLines(array $s,int $company,array $lines): void { if(count($lines)<2||!entryBalanced($lines))throw new RuntimeException('Jurnal multi-line tidak balance.');$am=accountMap($s);foreach($lines as $l){$aid=(int)($l['account_id']??0);$a=$am[$aid]??null;if(!$a)throw new InvalidArgumentException('Akun jurnal tidak ditemukan.');$owner=(int)($a['company_id']??0);if($owner!==0&&$owner!==$company)throw new RuntimeException('Akun jurnal bukan milik badan usaha yang dipilih.');if((float)($l['debit']??0)<0||(float)($l['credit']??0)<0||((float)($l['debit']??0)>0&&(float)($l['credit']??0)>0))throw new InvalidArgumentException('Baris jurnal tidak valid.');} }
function normalizeDailyIncomeInput(array $input,array $s): array { $company=(int)($input['company_id']??0);$date=(string)($input['date']??date('Y-m-d'));$description=trim((string)($input['description']??'Pendapatan harian'));if(!$company||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||textLength($description)<3)throw new InvalidArgumentException('Badan usaha, tanggal, dan keterangan pendapatan wajib diisi.');$incomeRaw=$input['income_lines']??[];$paymentRaw=$input['payment_lines']??[];if(is_string($incomeRaw))$incomeRaw=json_decode($incomeRaw,true);if(is_string($paymentRaw))$paymentRaw=json_decode($paymentRaw,true);if(!is_array($incomeRaw)||!is_array($paymentRaw))throw new InvalidArgumentException('Detail pendapatan/pembayaran tidak valid.');$cats=[];foreach($s['income_categories']??[] as $c)if((int)$c['company_id']===$company&&!empty($c['active']))$cats[(int)$c['id']]=$c;$am=accountMap($s);$lines=[];$incomeTotal=0.0;$paymentTotal=0.0;$normalizedIncome=[];$normalizedPayment=[];foreach($incomeRaw as $r){$cid=(int)($r['category_id']??0);$amt=(float)($r['amount']??0);if($amt<=0)continue;$cat=$cats[$cid]??null;if(!$cat)throw new InvalidArgumentException('Kategori pendapatan tidak tersedia untuk badan usaha ini.');$aid=(int)$cat['revenue_account_id'];$a=$am[$aid]??null;if(!$a||($a['type']??'')!=='revenue')throw new RuntimeException('Kategori pendapatan harus dipetakan ke akun revenue aktif.');$lines[]=['account_id'=>$aid,'debit'=>0.0,'credit'=>$amt,'description'=>(string)$cat['name']];$normalizedIncome[]=['category_id'=>$cid,'name'=>$cat['name'],'amount'=>$amt,'account_id'=>$aid];$incomeTotal+=$amt;}foreach($paymentRaw as $r){$aid=(int)($r['account_id']??0);$amt=(float)($r['amount']??0);$label=trim((string)($r['label']??'Kas / Bank'));if($amt<=0)continue;$a=$am[$aid]??null;if(!$a||empty($a['cash']))throw new InvalidArgumentException('Pembayaran harus masuk ke akun kas/bank aktif.');$owner=(int)($a['company_id']??0);if($owner!==0&&$owner!==$company)throw new RuntimeException('Akun pembayaran bukan milik badan usaha yang dipilih.');$lines[]=['account_id'=>$aid,'debit'=>$amt,'credit'=>0.0,'description'=>$label?:'Kas / Bank'];$normalizedPayment[]=['account_id'=>$aid,'label'=>$label?:'Kas / Bank','amount'=>$amt];$paymentTotal+=$amt;}if($incomeTotal<=0||$paymentTotal<=0)throw new InvalidArgumentException('Minimal satu pendapatan dan satu pembayaran harus bernilai lebih dari nol.');if(abs($incomeTotal-$paymentTotal)>0.01)throw new RuntimeException('Total pendapatan harus sama dengan total pembayaran. Selisih '.money(abs($incomeTotal-$paymentTotal)).'.');validateMultiJournalLines($s,$company,$lines);return ['kind'=>'daily_income','company'=>$company,'company_id'=>$company,'date'=>$date,'desc'=>$description,'description'=>$description,'amount'=>$incomeTotal,'total'=>$incomeTotal,'lines'=>$lines,'income_lines'=>$normalizedIncome,'payment_lines'=>$normalizedPayment]; }
function insertPostedMultiLineDb(PDO $pdo,array $j,string $source='daily_income'): array { $prefix=$source==='daily_income'?'INC':'JRN';$no=$prefix.'-'.str_replace('-','',substr($j['date'],0,7)).'-'.strtoupper(bin2hex(random_bytes(3)));$st=$pdo->prepare("INSERT INTO journal_entries(company_id,journal_no,journal_date,description,source_type,status,posted_at,created_by) VALUES(?,?,?,?,?,'posted',NOW(),?)");$st->execute([$j['company'],$no,$j['date'],$j['desc'],$source,$_SESSION['user_id']??null]);$jid=(int)$pdo->lastInsertId();$sl=$pdo->prepare("INSERT INTO journal_lines(journal_id,account_id,description,debit,credit,intercompany_company_id) VALUES(?,?,?,?,?,NULL)");foreach($j['lines'] as $l)$sl->execute([$jid,(int)$l['account_id'],(string)($l['description']??''),(float)$l['debit'],(float)$l['credit']]);return ['id'=>$jid,'no'=>$no,'status'=>'posted','source'=>$source,'amount'=>$j['amount']]; }
function postDailyIncome(array $input,bool $approvedOverride=false): array { global $config;$s=loadStore();requireAbility('income.manage',$s);$j=normalizeDailyIncomeInput($input,$s);enforceCompanyAccess($s,$j['company']);assertPeriodOpen($s,$j['date']);$threshold=(float)($s['meta']['approval_threshold']??25000000);$u=currentUser($s);$payload=['kind'=>'daily_income','company_id'=>$j['company'],'date'=>$j['date'],'description'=>$j['desc'],'income_lines'=>$j['income_lines'],'payment_lines'=>$j['payment_lines']];if($j['amount']>=$threshold&&!$approvedOverride){if($config['demo_mode']){$aid=(int)($s['meta']['next_approval_id']??1);$a=['id'=>$aid,'journal_id'=>null,'company_id'=>$j['company'],'date'=>$j['date'],'description'=>$j['desc'],'amount'=>$j['amount'],'requested_by'=>$u['id'],'status'=>'pending','requested_at'=>date('Y-m-d H:i:s'),'payload'=>$payload];$s['approvals'][]=$a;$s['meta']['next_approval_id']=$aid+1;saveStore($s);writeAudit('daily_income.approval_requested',['approval_id'=>$aid,'amount'=>$j['amount'],'company_id'=>$j['company']]);return ['approval_required'=>true,'approval'=>$a,'amount'=>$j['amount']];}$pdo=db();$st=$pdo->prepare("INSERT INTO journal_approvals(company_id,journal_date,description,amount,requested_by,status,payload_json) VALUES(?,?,?,?,?,'pending',?)");$st->execute([$j['company'],$j['date'],$j['desc'],$j['amount'],$u['id'],json_encode($payload,JSON_UNESCAPED_UNICODE)]);$aid=(int)$pdo->lastInsertId();writeAudit('daily_income.approval_requested',['approval_id'=>$aid,'amount'=>$j['amount'],'company_id'=>$j['company']]);return ['approval_required'=>true,'approval'=>['id'=>$aid,'status'=>'pending'],'amount'=>$j['amount']];}if($config['demo_mode']){$id=(int)($s['meta']['next_entry_id']??count($s['entries'])+1);$entry=['id'=>$id,'no'=>'INC-'.str_replace('-','',substr($j['date'],0,7)).'-'.str_pad((string)$id,4,'0',STR_PAD_LEFT),'company_id'=>$j['company'],'date'=>$j['date'],'description'=>$j['desc'],'status'=>'posted','source'=>'daily_income','intercompany_company_id'=>null,'lines'=>$j['lines']];$s['entries'][]=$entry;$s['meta']['next_entry_id']=$id+1;$s['meta']['version']=(int)($s['meta']['version']??0)+1;saveStore($s);writeAudit('daily_income.posted',['id'=>$id,'amount'=>$j['amount'],'company_id'=>$j['company']]);return $entry+['amount'=>$j['amount']];}$pdo=db();$pdo->beginTransaction();try{lockAndAssertPeriodOpenDb($pdo,$j['date']);$entry=insertPostedMultiLineDb($pdo,$j,'daily_income');$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}writeAudit('daily_income.posted',['id'=>$entry['id'],'amount'=>$j['amount'],'company_id'=>$j['company']]);return $entry; }
function createIncomeCategory(array $input): array { global $config;$s=loadStore();requireAbility('income.category.manage',$s);$company=(int)($input['company_id']??0);$name=trim((string)($input['name']??''));$code=strtoupper(trim((string)($input['code']??'')));$account=(int)($input['revenue_account_id']??0);if(!$company||textLength($name)<2||!preg_match('/^[A-Z0-9_-]{2,20}$/',$code)||!$account)throw new InvalidArgumentException('Data kategori pendapatan tidak valid.');enforceCompanyAccess($s,$company);$am=accountMap($s);$a=$am[$account]??null;if(!$a||($a['type']??'')!=='revenue')throw new InvalidArgumentException('Kategori harus dipetakan ke akun revenue.');foreach($s['income_categories']??[] as $c)if((int)$c['company_id']===$company&&strtoupper((string)$c['code'])===$code)throw new RuntimeException('Kode kategori sudah digunakan pada badan usaha ini.');if($config['demo_mode']){$id=(int)($s['meta']['next_income_category_id']??1);$row=['id'=>$id,'company_id'=>$company,'code'=>$code,'name'=>$name,'revenue_account_id'=>$account,'active'=>1,'sort_order'=>count($s['income_categories']??[])+10];$s['income_categories'][]=$row;$s['meta']['next_income_category_id']=$id+1;saveStore($s);writeAudit('income_category.created',['id'=>$id,'company_id'=>$company]);return $row;}$pdo=db();$st=$pdo->prepare("INSERT INTO income_categories(company_id,code,name,revenue_account_id,sort_order,is_active) VALUES(?,?,?,?,100,1)");$st->execute([$company,$code,$name,$account]);$row=['id'=>(int)$pdo->lastInsertId(),'company_id'=>$company,'code'=>$code,'name'=>$name,'revenue_account_id'=>$account,'active'=>1,'sort_order'=>100];writeAudit('income_category.created',['id'=>$row['id'],'company_id'=>$company]);return $row; }

function loginIdentifierHash(string $email): string { return hash('sha256',strtolower(trim($email))); }
function loginRateAllowed(PDO $pdo,string $email,string $ip,int $max=8,int $minutes=15): bool { $st=$pdo->prepare("SELECT COUNT(*) FROM login_attempts WHERE identifier_hash=? AND ip_address=? AND success=0 AND attempted_at>=DATE_SUB(NOW(),INTERVAL ? MINUTE)");$st->execute([loginIdentifierHash($email),$ip,$minutes]);return (int)$st->fetchColumn()<$max; }
function recordLoginAttempt(PDO $pdo,string $email,string $ip,bool $success): void { $st=$pdo->prepare("INSERT INTO login_attempts(identifier_hash,ip_address,success) VALUES(?,?,?)");$st->execute([loginIdentifierHash($email),$ip,$success?1:0]);if($success){$pdo->prepare("DELETE FROM login_attempts WHERE identifier_hash=? AND ip_address=? AND success=0")->execute([loginIdentifierHash($email),$ip]);}$pdo->exec("DELETE FROM login_attempts WHERE attempted_at<DATE_SUB(NOW(),INTERVAL 2 DAY)"); }
function currentUser(array $s): array { global $config; if($config['demo_mode']){ $id=(int)($_SESSION['user_id']??1); foreach(($s['users']??[]) as $u) if((int)$u['id']===$id) return $u; return ['id'=>1,'name'=>'Group Owner','email'=>'owner@nexa.local','role'=>'group_owner','active'=>1]; } $id=(int)($_SESSION['user_id']??0); if(!$id)return []; foreach(($s['users']??[]) as $u)if((int)$u['id']===$id&&!empty($u['active']))return $u; return []; }
function isAuthenticated(): bool { global $config; if($config['demo_mode'])return true; return !empty($_SESSION['user_id']); }
function requireLogin(bool $api=false): void { if(isAuthenticated())return; if($api)jsonOut(['ok'=>false,'message'=>'Autentikasi diperlukan.'],401); header('Location: login.php'); exit; }
function scopeStoreForUser(array $s,array $u): array {
    if(($u['role']??'')!=='entity_admin')return $s;
    $cid=(int)($u['company_id']??0);
    $direct=['companies','accounts','entries','branches','departments','budgets','assets','invoices','bank_feed','bank_accounts','approvals','payments','integration_staging','fx_events','eliminations','parties','tax_transactions','expense_categories','bank_transfers','opening_balance_batches','cash_forecast_items','year_end_closes','onboarding_import_jobs','ap_payment_batches','document_attachments','employee_advances','loan_facilities','equity_transactions','budget_scenarios'];
    if(!$cid){foreach(array_merge($direct,['recurring_journal_templates','recurring_journal_runs','onboarding_import_errors','ap_payment_batch_lines','employee_advance_settlements','loan_payments','budget_scenario_lines']) as $k)$s[$k]=[];return $s;}
    $s['companies']=array_values(array_filter($s['companies']??[],fn($r)=>(int)$r['id']===$cid));
    $s['accounts']=array_values(array_filter($s['accounts']??[],fn($r)=>(int)($r['company_id']??0)===0||(int)($r['company_id']??0)===$cid));
    $s['entries']=array_values(array_filter($s['entries']??[],fn($r)=>(int)$r['company_id']===$cid));
    foreach(array_diff($direct,['companies','accounts','entries','eliminations']) as $k)$s[$k]=array_values(array_filter($s[$k]??[],fn($r)=>(int)($r['company_id']??0)===$cid));
    $s['recurring_journal_templates']=array_values(array_filter($s['recurring_journal_templates']??[],fn($r)=>(int)($r['company_id']??0)===$cid));
    $recIds=array_flip(array_map(fn($r)=>(int)$r['id'],$s['recurring_journal_templates']));
    $s['recurring_journal_runs']=array_values(array_filter($s['recurring_journal_runs']??[],fn($r)=>isset($recIds[(int)($r['template_id']??0)])));
    $jobIds=array_flip(array_map(fn($r)=>(int)$r['id'],$s['onboarding_import_jobs']??[]));
    $s['onboarding_import_errors']=array_values(array_filter($s['onboarding_import_errors']??[],fn($r)=>isset($jobIds[(int)($r['job_id']??0)])));
    $batchIds=array_flip(array_map(fn($r)=>(int)$r['id'],$s['ap_payment_batches']??[]));
    $s['ap_payment_batch_lines']=array_values(array_filter($s['ap_payment_batch_lines']??[],fn($r)=>isset($batchIds[(int)($r['batch_id']??0)])));
    $s['eliminations']=array_values(array_filter($s['eliminations']??[],fn($r)=>(int)($r['from_company_id']??0)===$cid||(int)($r['to_company_id']??0)===$cid));
    return $s;
}
function roleCan(string $role,string $ability): bool { static $svc=null;global $config;$aliases=['journal.create'=>'journal.post','journal.approve'=>'approval.decide','period.manage'=>'period.close','intercompany.eliminate'=>'consolidation.manage','income.category.manage'=>'income.manage','backup.create'=>'backup.manage','user.manage'=>'user.manage','company.manage'=>'company.manage','audit.view'=>'audit.view'];$permission=$aliases[$ability]??$ability;if($svc===null){$pdo=null;if(!$config['demo_mode']){try{$pdo=db();}catch(Throwable){$pdo=null;}}$svc=new \Nexa\Security\RbacService($pdo);}return $svc->can($role,$permission); }
function enforceCompanyAccess(array $s,int $companyId): void { $u=currentUser($s); if(!$u)throw new RuntimeException('Autentikasi diperlukan.'); if(($u['role']??'')==='entity_admin' && (int)($u['company_id']??0)!==$companyId) throw new RuntimeException('Entity Admin hanya dapat mengelola badan usaha yang ditugaskan.'); }
function requireAbility(string $ability, ?array $store=null): void { $s=$store??loadStore(); $u=currentUser($s); if(!$u)throw new RuntimeException('Autentikasi diperlukan.'); if(!roleCan((string)$u['role'],$ability)) throw new RuntimeException('Akses ditolak untuk role '.$u['role'].'.'); }
function periodStatus(array $s,string $date): string { $ts=strtotime($date);$y=(int)date('Y',$ts);$m=(int)date('n',$ts); foreach(($s['periods']??[]) as $p) if((int)$p['year']===$y&&(int)$p['month']===$m)return (string)$p['status']; return 'open'; }
function assertPeriodOpen(array $s,string $date): void { if(periodStatus($s,$date)!=='open') throw new RuntimeException('Periode akuntansi '.date('m/Y',strtotime($date)).' sudah ditutup.'); }
function agingBucket(string $dueDate,?string $asOf=null): string { $asOf=$asOf?:date('Y-m-d'); $days=(int)floor((strtotime($asOf)-strtotime($dueDate))/86400); if($days<=0)return 'Current'; if($days<=30)return '1-30'; if($days<=60)return '31-60'; if($days<=90)return '61-90'; return '90+'; }
function arapSummary(array $s): array { $out=['receivable'=>0.0,'payable'=>0.0,'overdue_receivable'=>0.0,'overdue_payable'=>0.0,'rows'=>[],'aging'=>['Current'=>0.0,'1-30'=>0.0,'31-60'=>0.0,'61-90'=>0.0,'90+'=>0.0]]; foreach(($s['invoices']??[]) as $i){$open=max(0,(float)$i['amount']-(float)$i['paid']);$type=(string)$i['type'];$out[$type]+=$open;$bucket=agingBucket((string)$i['due_date']);if($type==='receivable')$out['aging'][$bucket]+=$open;if(strtotime((string)$i['due_date'])<strtotime(date('Y-m-d'))&&$open>0)$out['overdue_'.$type]+=$open;$r=$i;$r['open']=$open;$r['bucket']=$bucket;$out['rows'][]=$r;} return $out; }
function bankReconciliationSummary(array $s): array { $matched=$unmatched=$in=$out=0.0;$rows=$s['bank_feed']??[]; foreach($rows as $r){$amt=(float)$r['amount']; if($r['status']==='matched')$matched+=$amt;else$unmatched+=$amt;if($r['direction']==='in')$in+=$amt;else$out+=$amt;} return compact('matched','unmatched','in','out','rows')+['match_rate'=>($matched+$unmatched)>0?$matched/($matched+$unmatched)*100:0]; }
function approvalSummary(array $s): array { $pending=0.0;$approved=0.0;$count=0;foreach(($s['approvals']??[]) as $a){if($a['status']==='pending'){$pending+=(float)$a['amount'];$count++;}elseif($a['status']==='approved')$approved+=(float)$a['amount'];}return compact('pending','approved','count')+['rows'=>$s['approvals']??[]]; }
function closePeriod(int $year,int $month): array { global $config;if($year<2000||$month<1||$month>12)throw new InvalidArgumentException('Periode tidak valid.');$s=loadStore();requireAbility('period.manage',$s);$u=currentUser($s);$prefix=sprintf('%04d-%02d',$year,$month);$pending=array_filter($s['approvals']??[],fn($a)=>($a['status']??'')==='pending'&&str_starts_with((string)($a['date']??''),$prefix));if($pending)throw new RuntimeException('Periode belum dapat ditutup karena masih ada approval jurnal pending.');if($config['demo_mode']){$found=false;foreach($s['periods'] as &$p){if((int)$p['year']===$year&&(int)$p['month']===$month){$p['status']='closed';$p['closed_at']=date('Y-m-d H:i:s');$p['closed_by']=$u['id'];$found=true;}}unset($p);if(!$found)$s['periods'][]=['id'=>count($s['periods'])+1,'year'=>$year,'month'=>$month,'status'=>'closed','closed_at'=>date('Y-m-d H:i:s'),'closed_by'=>$u['id']];saveStore($s);writeAudit('period.closed',['year'=>$year,'month'=>$month]);return ['year'=>$year,'month'=>$month,'status'=>'closed'];}$pdo=db();$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO fiscal_periods(fiscal_year,period,status) VALUES(?,?,'open') ON DUPLICATE KEY UPDATE id=id")->execute([$year,$month]);$st=$pdo->prepare("SELECT status FROM fiscal_periods WHERE fiscal_year=? AND period=? FOR UPDATE");$st->execute([$year,$month]);$st->fetchColumn();$q=$pdo->prepare("SELECT COUNT(*) FROM journal_approvals WHERE status='pending' AND YEAR(journal_date)=? AND MONTH(journal_date)=?");$q->execute([$year,$month]);if((int)$q->fetchColumn()>0)throw new RuntimeException('Periode belum dapat ditutup karena masih ada approval jurnal pending.');$up=$pdo->prepare("UPDATE fiscal_periods SET status='closed',closed_at=NOW(),closed_by=? WHERE fiscal_year=? AND period=?");$up->execute([$u['id'],$year,$month]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}writeAudit('period.closed',['year'=>$year,'month'=>$month]);return ['year'=>$year,'month'=>$month,'status'=>'closed']; }
function reconcileBank(int $bankId,int $journalId): array { global $config;$s=loadStore();requireAbility('bank.reconcile',$s);if($bankId<=0||$journalId<=0)throw new InvalidArgumentException('Mutasi bank dan jurnal wajib dipilih.');$bank=null;foreach($s['bank_feed']??[] as $r)if((int)$r['id']===$bankId)$bank=$r;$entry=findEntry($s,$journalId);if(!$bank||!$entry)throw new InvalidArgumentException('Mutasi bank atau jurnal tidak ditemukan.');enforceCompanyAccess($s,(int)$bank['company_id']);if((int)$entry['company_id']!==(int)$bank['company_id'])throw new RuntimeException('Jurnal dan mutasi bank harus berasal dari badan usaha yang sama.');$am=accountMap($s);$cash=0.0;foreach($entry['lines'] as $l){$a=$am[(int)$l['account_id']]??null;if($a&&!empty($a['cash']))$cash+=(float)$l['debit']-(float)$l['credit'];}$expected=$bank['direction']==='in'?(float)$bank['amount']:-(float)$bank['amount'];if(abs($cash-$expected)>0.01)throw new RuntimeException('Nominal/direction jurnal kas tidak cocok dengan mutasi bank.');if(($bank['status']??'')!=='unmatched')throw new RuntimeException('Mutasi bank sudah direkonsiliasi atau diabaikan.');if($config['demo_mode']){foreach($s['bank_feed'] as &$r)if((int)$r['id']===$bankId){$r['status']='matched';$r['journal_id']=$journalId;$bank=$r;}unset($r);saveStore($s);writeAudit('bank.reconciled',['bank_id'=>$bankId,'journal_id'=>$journalId]);return $bank;}$pdo=db();$pdo->beginTransaction();try{$st=$pdo->prepare("SELECT status FROM bank_feed WHERE id=? FOR UPDATE");$st->execute([$bankId]);if($st->fetchColumn()!=='unmatched')throw new RuntimeException('Mutasi bank sudah direkonsiliasi atau diabaikan.');$up=$pdo->prepare("UPDATE bank_feed SET status='matched',journal_id=? WHERE id=? AND status='unmatched'");$up->execute([$journalId,$bankId]);if($up->rowCount()!==1)throw new RuntimeException('Rekonsiliasi gagal karena data berubah.');$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}writeAudit('bank.reconciled',['bank_id'=>$bankId,'journal_id'=>$journalId]);return ['id'=>$bankId,'journal_id'=>$journalId,'status'=>'matched']; }
function decideApproval(int $id,string $decision): array { global $config;$s=loadStore();requireAbility('journal.approve',$s);if(!in_array($decision,['approved','rejected'],true))throw new InvalidArgumentException('Keputusan approval tidak valid.');$u=currentUser($s);
    if($config['demo_mode']){
        $found=null;foreach($s['approvals'] as $a)if((int)$a['id']===$id){$found=$a;break;}if(!$found)throw new InvalidArgumentException('Approval tidak ditemukan.');if($found['status']!=='pending')throw new RuntimeException('Approval sudah diputuskan.');$posted=null;if($decision==='approved'){if(!is_array($found['payload']??null))throw new RuntimeException('Payload approval tidak lengkap.');$posted=(($found['payload']['kind']??'')==='daily_income')?postDailyIncome($found['payload'],true):postJournal($found['payload'],true);$s=loadStore();}foreach($s['approvals'] as &$a)if((int)$a['id']===$id){$a['status']=$decision;$a['decided_at']=date('Y-m-d H:i:s');$a['decided_by']=$u['id'];if($posted)$a['journal_id']=$posted['id']??null;$row=$a;}unset($a);saveStore($s);if($posted)$row['posted_entry']=$posted;writeAudit('approval.'.$decision,['approval_id'=>$id]);return $row;
    }
    $pdo=db();$pdo->beginTransaction();try{$st=$pdo->prepare("SELECT * FROM journal_approvals WHERE id=? FOR UPDATE");$st->execute([$id]);$row=$st->fetch();if(!$row)throw new InvalidArgumentException('Approval tidak ditemukan.');if($row['status']!=='pending')throw new RuntimeException('Approval sudah diputuskan.');$posted=null;if($decision==='approved'){$payload=$row['payload_json']?json_decode((string)$row['payload_json'],true):null;if(!is_array($payload))throw new RuntimeException('Payload approval tidak lengkap.');if(($payload['kind']??'')==='daily_income'){$j=normalizeDailyIncomeInput($payload,$s);requireAbility('income.manage',$s);enforceCompanyAccess($s,$j['company']);lockAndAssertPeriodOpenDb($pdo,$j['date']);$posted=insertPostedMultiLineDb($pdo,$j,'daily_income');}else{$j=normalizeJournalInput($payload);requireAbility('journal.create',$s);enforceCompanyAccess($s,$j['company']);validateJournalAccounts($s,$j['company'],$j['debit'],$j['credit']);validateIntercompany($s,$j['company'],$j['ic']);lockAndAssertPeriodOpenDb($pdo,$j['date']);$posted=insertPostedJournalDb($pdo,$j,'manual');}}$up=$pdo->prepare("UPDATE journal_approvals SET status=?,journal_id=?,decided_at=NOW(),decided_by=? WHERE id=?");$up->execute([$decision,$posted['id']??null,$u['id'],$id]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}writeAudit('approval.'.$decision,['approval_id'=>$id,'journal_id'=>$posted['id']??null]);$row['status']=$decision;if($posted)$row['posted_entry']=$posted;return $row;
}
function writeAudit(string $action, array $payload=[]): void { global $config;$name=$_SESSION['user_name']??'system'; $r=['at'=>date('c'),'user'=>$name,'action'=>$action,'ip'=>$_SERVER['REMOTE_ADDR']??'cli','payload'=>$payload]; @file_put_contents(auditPath(),json_encode($r,JSON_UNESCAPED_UNICODE).PHP_EOL,FILE_APPEND|LOCK_EX); if(!$config['demo_mode']){try{$pdo=db();if($pdo){$st=$pdo->prepare("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,payload_json,ip_address) VALUES(?,?,?,?,?,?)");$st->execute([$_SESSION['user_id']??null,$action,$payload['entity_type']??'system',(string)($payload['id']??$payload['approval_id']??''),json_encode($payload,JSON_UNESCAPED_UNICODE),$_SERVER['REMOTE_ADDR']??'cli']);}}catch(Throwable $e){error_log('NEXA audit DB: '.$e->getMessage());}} }
function postJournal(array $input,bool $approvedOverride=false): array { global $config;$j=normalizeJournalInput($input);$lines=[['account_id'=>$j['debit'],'debit'=>$j['amount'],'credit'=>0],['account_id'=>$j['credit'],'debit'=>0,'credit'=>$j['amount']]];if(!entryBalanced($lines))throw new RuntimeException('Jurnal tidak balance.');$s=loadStore();requireAbility('journal.create',$s);enforceCompanyAccess($s,$j['company']);validateJournalAccounts($s,$j['company'],$j['debit'],$j['credit']);validateIntercompany($s,$j['company'],$j['ic']);assertPeriodOpen($s,$j['date']);$threshold=(float)($s['meta']['approval_threshold']??25000000);
    if($config['demo_mode']){
        if($j['amount']>=$threshold&&!$approvedOverride){$aid=(int)($s['meta']['next_approval_id']??1);$payload=['company_id'=>$j['company'],'date'=>$j['date'],'description'=>$j['desc'],'amount'=>$j['amount'],'debit_account_id'=>$j['debit'],'credit_account_id'=>$j['credit'],'intercompany_company_id'=>$j['ic']];$a=['id'=>$aid,'journal_id'=>null,'company_id'=>$j['company'],'date'=>$j['date'],'description'=>$j['desc'],'amount'=>$j['amount'],'requested_by'=>currentUser($s)['id'],'status'=>'pending','requested_at'=>date('Y-m-d H:i:s'),'payload'=>$payload];$s['approvals'][]=$a;$s['meta']['next_approval_id']=$aid+1;saveStore($s);writeAudit('journal.approval_requested',['approval_id'=>$aid,'amount'=>$j['amount']]);return ['approval_required'=>true,'approval'=>$a];}
        $id=(int)($s['meta']['next_entry_id']??(count($s['entries'])+1));$entry=['id'=>$id,'no'=>'JRN-'.str_replace('-','',substr($j['date'],0,7)).'-'.str_pad((string)$id,4,'0',STR_PAD_LEFT),'company_id'=>$j['company'],'date'=>$j['date'],'description'=>$j['desc'],'status'=>'posted','source'=>'manual','intercompany_company_id'=>$j['ic'],'lines'=>$lines];$s['entries'][]=$entry;$s['meta']['next_entry_id']=$id+1;$s['meta']['version']=(int)($s['meta']['version']??0)+1;saveStore($s);writeAudit('journal.posted',['id'=>$id,'amount'=>$j['amount']]);return $entry;
    }
    $pdo=db();if($j['amount']>=$threshold&&!$approvedOverride){$u=currentUser($s);$payload=['company_id'=>$j['company'],'date'=>$j['date'],'description'=>$j['desc'],'amount'=>$j['amount'],'debit_account_id'=>$j['debit'],'credit_account_id'=>$j['credit'],'intercompany_company_id'=>$j['ic']];$st=$pdo->prepare("INSERT INTO journal_approvals(company_id,journal_date,description,amount,requested_by,status,payload_json) VALUES(?,?,?,?,?,'pending',?)");$st->execute([$j['company'],$j['date'],$j['desc'],$j['amount'],$u['id'],json_encode($payload,JSON_UNESCAPED_UNICODE)]);$aid=(int)$pdo->lastInsertId();writeAudit('journal.approval_requested',['approval_id'=>$aid,'amount'=>$j['amount']]);return ['approval_required'=>true,'approval'=>['id'=>$aid,'status'=>'pending']];}
    $pdo->beginTransaction();try{lockAndAssertPeriodOpenDb($pdo,$j['date']);$entry=insertPostedJournalDb($pdo,$j,'manual');$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}writeAudit('journal.posted',['id'=>$entry['id'],'amount'=>$j['amount']]);return $entry;
}

function findEntry(array $s,int $id): ?array { foreach(($s['entries']??[]) as $e)if((int)$e['id']===$id)return $e; return null; }
function journalAmount(array $e): float { $m=0.0;foreach(($e['lines']??[]) as $l)$m=max($m,(float)$l['debit'],(float)$l['credit']);return $m; }
function reverseJournal(int $id,string $reason): array { global $config;$reason=trim($reason);if($id<=0||$reason==='')throw new InvalidArgumentException('Jurnal dan alasan reversal wajib diisi.');$s=loadStore();requireAbility('journal.reverse',$s);$orig=findEntry($s,$id);if(!$orig)throw new InvalidArgumentException('Jurnal tidak ditemukan.');enforceCompanyAccess($s,(int)$orig['company_id']);$reverseDate=date('Y-m-d');assertPeriodOpen($s,$reverseDate);if(($orig['status']??'')!=='posted')throw new RuntimeException('Hanya jurnal posted yang dapat direversal.');if(!empty($orig['reversal_of'])||!empty($orig['reversed_by']))throw new RuntimeException('Jurnal reversal/yang sudah direversal tidak dapat direversal ulang.');$lines=array_map(fn($l)=>['account_id'=>(int)$l['account_id'],'debit'=>(float)$l['credit'],'credit'=>(float)$l['debit']],$orig['lines']);if(!entryBalanced($lines))throw new RuntimeException('Reversal gagal balance.');
    if($config['demo_mode']){$nid=(int)($s['meta']['next_entry_id']??count($s['entries'])+1);$rev=['id'=>$nid,'no'=>'REV-'.date('Ym').'-'.str_pad((string)$nid,4,'0',STR_PAD_LEFT),'company_id'=>(int)$orig['company_id'],'date'=>$reverseDate,'description'=>'REVERSAL '.$orig['no'].' · '.$reason,'status'=>'posted','source'=>'reversal','intercompany_company_id'=>$orig['intercompany_company_id']??null,'reversal_of'=>$id,'lines'=>$lines];foreach($s['entries'] as &$e)if((int)$e['id']===$id)$e['reversed_by']=$nid;unset($e);$s['entries'][]=$rev;$s['meta']['next_entry_id']=$nid+1;saveStore($s);writeAudit('journal.reversed',['id'=>$id,'reversal_id'=>$nid,'reason'=>$reason]);return $rev;}
    $pdo=db();$pdo->beginTransaction();try{lockAndAssertPeriodOpenDb($pdo,$reverseDate);$lock=$pdo->prepare("SELECT reversal_of,reversed_by,status FROM journal_entries WHERE id=? FOR UPDATE");$lock->execute([$id]);$dbOrig=$lock->fetch();if(!$dbOrig||$dbOrig['status']!=='posted')throw new RuntimeException('Jurnal tidak tersedia untuk reversal.');if(!empty($dbOrig['reversal_of'])||!empty($dbOrig['reversed_by']))throw new RuntimeException('Jurnal reversal/yang sudah direversal tidak dapat direversal ulang.');$no='REV-'.date('YmHis').'-'.$id;$st=$pdo->prepare("INSERT INTO journal_entries(company_id,journal_no,journal_date,description,status,source_type,created_by,posted_at,reversal_of) VALUES(?,?,?,?, 'posted','reversal',?,NOW(),?)");$st->execute([$orig['company_id'],$no,$reverseDate,'REVERSAL '.$orig['no'].' · '.$reason,$_SESSION['user_id']??null,$id]);$nid=(int)$pdo->lastInsertId();$li=$pdo->prepare("INSERT INTO journal_lines(journal_id,account_id,debit,credit,intercompany_company_id) VALUES(?,?,?,?,?)");foreach($lines as $l)$li->execute([$nid,$l['account_id'],$l['debit'],$l['credit'],$orig['intercompany_company_id']??null]);$pdo->prepare("UPDATE journal_entries SET reversed_by=? WHERE id=?")->execute([$nid,$id]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}writeAudit('journal.reversed',['id'=>$id,'reversal_id'=>$nid,'reason'=>$reason]);return ['id'=>$nid,'no'=>$no,'status'=>'posted'];
}
function allocateInvoicePayment(int $invoiceId,float $amount,string $date,string $method='bank',string $reference=''): array { global $config;if($invoiceId<=0||$amount<=0||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))throw new InvalidArgumentException('Invoice, nominal, atau tanggal pembayaran tidak valid.');$s=loadStore();requireAbility('arap.manage',$s);$inv=null;foreach(($s['invoices']??[]) as $i)if((int)$i['id']===$invoiceId)$inv=$i;if(!$inv)throw new InvalidArgumentException('Invoice tidak ditemukan.');enforceCompanyAccess($s,(int)$inv['company_id']);assertPeriodOpen($s,$date);$threshold=(float)($s['meta']['approval_threshold']??25000000);$u=currentUser($s);if($amount>=$threshold&&!roleCan((string)($u['role']??''),'journal.approve'))throw new RuntimeException('Pembayaran di atas batas approval harus diproses Group Finance/Owner.');$cashAccount=accountIdByCode($s,(int)$inv['company_id'],'1101');$arAccount=accountIdByCode($s,(int)$inv['company_id'],'1102');$apAccount=accountIdByCode($s,(int)$inv['company_id'],'2101');$debit=$inv['type']==='receivable'?$cashAccount:$apAccount;$credit=$inv['type']==='receivable'?$arAccount:$cashAccount;validateJournalAccounts($s,(int)$inv['company_id'],$debit,$credit);
    if($config['demo_mode']){$open=max(0,(float)$inv['amount']-(float)$inv['paid']);if($amount>$open+0.005)throw new RuntimeException('Pembayaran melebihi saldo invoice.');$entry=postJournal(['company_id'=>$inv['company_id'],'date'=>$date,'description'=>'Pembayaran '.$inv['number'].' · '.$inv['party'],'amount'=>$amount,'debit_account_id'=>$debit,'credit_account_id'=>$credit],true);$pid=(int)($s['meta']['next_payment_id']??1);$s=loadStore();foreach($s['invoices'] as &$i)if((int)$i['id']===$invoiceId){$i['paid']=(float)$i['paid']+$amount;$i['status']=$i['paid']+0.005>=(float)$i['amount']?'paid':'partial';$inv=$i;}unset($i);$pay=['id'=>$pid,'invoice_id'=>$invoiceId,'company_id'=>$inv['company_id'],'date'=>$date,'amount'=>$amount,'method'=>$method,'reference'=>$reference,'journal_id'=>$entry['id']];$s['payments'][]=$pay;$s['meta']['next_payment_id']=$pid+1;saveStore($s);writeAudit('invoice.payment_allocated',['invoice_id'=>$invoiceId,'payment_id'=>$pid,'amount'=>$amount]);return $pay;}
    $pdo=db();$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT id,company_id,invoice_type,invoice_no,party_name,amount,paid_amount,status FROM invoices WHERE id=? FOR UPDATE");$q->execute([$invoiceId]);$locked=$q->fetch();if(!$locked||$locked['status']==='void')throw new RuntimeException('Invoice tidak tersedia.');$open=max(0,(float)$locked['amount']-(float)$locked['paid_amount']);if($amount>$open+0.005)throw new RuntimeException('Pembayaran melebihi saldo invoice.');lockAndAssertPeriodOpenDb($pdo,$date);$j=['company'=>(int)$locked['company_id'],'date'=>$date,'desc'=>'Pembayaran '.$locked['invoice_no'].' · '.$locked['party_name'],'amount'=>$amount,'debit'=>$debit,'credit'=>$credit,'ic'=>null];$entry=insertPostedJournalDb($pdo,$j,'arap_payment');$pdo->prepare("UPDATE invoices SET paid_amount=paid_amount+?, status=CASE WHEN paid_amount+?>=amount THEN 'paid' ELSE 'partial' END WHERE id=?")->execute([$amount,$amount,$invoiceId]);$st=$pdo->prepare("INSERT INTO invoice_payments(invoice_id,company_id,payment_date,amount,method,reference_no,journal_id,created_by) VALUES(?,?,?,?,?,?,?,?)");$st->execute([$invoiceId,$locked['company_id'],$date,$amount,$method,$reference,$entry['id'],$u['id']]);$pid=(int)$pdo->lastInsertId();$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}writeAudit('invoice.payment_allocated',['invoice_id'=>$invoiceId,'payment_id'=>$pid,'amount'=>$amount]);return ['id'=>$pid,'journal_id'=>$entry['id'],'amount'=>$amount];
}
function createElimination(int $from,int $to,float $amount,string $period,string $description): array { global $config;$s=loadStore();requireAbility('intercompany.eliminate',$s);if($from<=0||$to<=0||$from===$to||$amount<=0||!preg_match('/^\d{4}-\d{2}$/',$period))throw new InvalidArgumentException('Data eliminasi intercompany tidak valid.');$cm=companyMap($s);if(!isset($cm[$from])||!isset($cm[$to]))throw new InvalidArgumentException('Badan usaha eliminasi tidak ditemukan.');assertPeriodOpen($s,$period.'-01');$row=['from_company_id'=>$from,'to_company_id'=>$to,'amount'=>$amount,'period'=>$period,'description'=>trim($description)?:'Intercompany elimination','status'=>'posted','created_at'=>date('Y-m-d H:i:s')];if($config['demo_mode']){$id=(int)($s['meta']['next_elimination_id']??1);$row['id']=$id;$s['eliminations'][]=$row;$s['meta']['next_elimination_id']=$id+1;saveStore($s);writeAudit('intercompany.eliminated',['id'=>$id,'amount'=>$amount,'period'=>$period]);return $row;}$pdo=db();$pdo->beginTransaction();try{lockAndAssertPeriodOpenDb($pdo,$period.'-01');$st=$pdo->prepare("INSERT INTO intercompany_eliminations(period_key,from_company_id,to_company_id,amount,description,status,created_by) VALUES(?,?,?,?,?,'posted',?)");$st->execute([$period,$from,$to,$amount,$row['description'],$_SESSION['user_id']??null]);$row['id']=(int)$pdo->lastInsertId();$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}writeAudit('intercompany.eliminated',['id'=>$row['id'],'amount'=>$amount,'period'=>$period]);return $row;}
function eliminationSummary(array $s): array { $total=0.0;foreach(($s['eliminations']??[]) as $r)if(($r['status']??'')==='posted')$total+=(float)$r['amount'];return ['total'=>$total,'count'=>count($s['eliminations']??[]),'rows'=>$s['eliminations']??[]]; }
function taxSummary(array $s): array { $active=array_values(array_filter($s['tax_profiles']??[],fn($x)=>!empty($x['active'])));return ['profiles'=>$active,'count'=>count($active)]; }
function calculateTax(float $base,float $rate,bool $inclusive=false): array { if($base<0||$rate<0)throw new InvalidArgumentException('Nilai pajak tidak valid.');$r=(new \Nexa\Legacy\EnterpriseFacade())->tax((int)round($base),$rate,$inclusive);return ['base'=>(float)$r['base'],'tax'=>(float)$r['tax'],'gross'=>(float)$r['gross'],'rate'=>$rate]; }
function recordFxEvent(int $company,string $date,string $currency,float $foreign,float $bookRate,float $settlementRate,string $description=''): array { global $config;$s=loadStore();requireAbility('fx.manage',$s);enforceCompanyAccess($s,$company);assertPeriodOpen($s,$date);$currency=strtoupper(trim($currency));$known=array_column($s['currencies']??[],'code');if($currency==='IDR'||!in_array($currency,$known,true)||$foreign<=0||$bookRate<=0||$settlementRate<=0)throw new InvalidArgumentException('Data FX atau mata uang tidak valid.');$base=$foreign*$bookRate;$settled=$foreign*$settlementRate;$gainLoss=$settled-$base;$row=['company_id'=>$company,'date'=>$date,'currency'=>$currency,'foreign_amount'=>$foreign,'book_rate'=>$bookRate,'settlement_rate'=>$settlementRate,'base_amount'=>$base,'gain_loss'=>$gainLoss,'description'=>$description];if($config['demo_mode']){$row['id']=count($s['fx_events']??[])+1;$s['fx_events'][]=$row;saveStore($s);writeAudit('fx.recorded',['id'=>$row['id'],'gain_loss'=>$gainLoss]);return $row;}$pdo=db();$pdo->beginTransaction();try{lockAndAssertPeriodOpenDb($pdo,$date);$st=$pdo->prepare("INSERT INTO fx_events(company_id,event_date,currency,foreign_amount,book_rate,settlement_rate,base_amount,gain_loss,description,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)");$st->execute([$company,$date,$currency,$foreign,$bookRate,$settlementRate,$base,$gainLoss,$description,$_SESSION['user_id']??null]);$row['id']=(int)$pdo->lastInsertId();$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}writeAudit('fx.recorded',['id'=>$row['id'],'gain_loss'=>$gainLoss]);return $row;}
function fxSummary(array $s): array { $gl=0.0;foreach(($s['fx_events']??[]) as $r)$gl+=(float)$r['gain_loss'];return ['gain_loss'=>$gl,'count'=>count($s['fx_events']??[]),'rows'=>$s['fx_events']??[]]; }
function importBankCsv(int $companyId,string $csv): array { global $config;$s=loadStore();requireAbility('bank.import',$s);enforceCompanyAccess($s,$companyId);$fh=fopen('php://temp','r+');fwrite($fh,$csv);rewind($fh);$head=fgetcsv($fh);if(!$head)throw new InvalidArgumentException('CSV kosong.');$map=array_flip(array_map(fn($x)=>strtolower(trim((string)$x)),$head));foreach(['date','description','amount','direction'] as $k)if(!isset($map[$k]))throw new InvalidArgumentException('CSV wajib memiliki kolom date,description,amount,direction.');$rows=[];while(($r=fgetcsv($fh))!==false){$date=trim($r[$map['date']]??'');$desc=trim($r[$map['description']]??'');$amount=(float)str_replace([',',' '],['',''],$r[$map['amount']]??0);$dir=strtolower(trim($r[$map['direction']]??''));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$desc===''||$amount<=0||!in_array($dir,['in','out'],true))continue;$rows[]=['company_id'=>$companyId,'date'=>$date,'description'=>$desc,'amount'=>$amount,'direction'=>$dir,'status'=>'unmatched','journal_id'=>null,'external_ref'=>'CSV-'.substr(hash('sha256',$date.'|'.$desc.'|'.$amount.'|'.$dir),0,20)];}fclose($fh);if(!$rows)throw new RuntimeException('Tidak ada baris bank valid yang dapat diimpor.');$imported=[];$skipped=0;if($config['demo_mode']){$existing=[];foreach($s['bank_feed']??[] as $x)$existing[(int)$x['company_id'].'|'.($x['external_ref']??'')]=1;$next=(int)($s['meta']['next_bank_id']??1);foreach($rows as $r){$key=$companyId.'|'.$r['external_ref'];if(isset($existing[$key])){$skipped++;continue;}$r['id']=$next++;$s['bank_feed'][]=$r;$imported[]=$r;$existing[$key]=1;}$s['meta']['next_bank_id']=$next;saveStore($s);writeAudit('bank.csv_imported',['company_id'=>$companyId,'rows'=>count($imported),'skipped'=>$skipped]);return ['count'=>count($imported),'skipped'=>$skipped,'rows'=>$imported];}$pdo=db();$pdo->beginTransaction();try{$st=$pdo->prepare("INSERT IGNORE INTO bank_feed(company_id,txn_date,description,amount,direction,status,external_ref) VALUES(?,?,?,?,?,'unmatched',?)");foreach($rows as $r){$st->execute([$companyId,$r['date'],$r['description'],$r['amount'],$r['direction'],$r['external_ref']]);if($st->rowCount()===1)$imported[]=$r;else$skipped++;}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}writeAudit('bank.csv_imported',['company_id'=>$companyId,'rows'=>count($imported),'skipped'=>$skipped]);return ['count'=>count($imported),'skipped'=>$skipped,'rows'=>$imported];}

function createCompany(array $input): array { global $config;$s=loadStore();requireAbility('company.manage',$s);$code=strtoupper(trim((string)($input['code']??'')));$name=trim((string)($input['name']??''));$type=trim((string)($input['business_type']??''));if(!preg_match('/^[A-Z0-9_-]{2,20}$/',$code)||textLength($name)<3||textLength($type)<2)throw new InvalidArgumentException('Kode, nama, atau jenis usaha tidak valid.');foreach($s['companies']??[] as $c)if(strtoupper((string)$c['code'])===$code)throw new RuntimeException('Kode badan usaha sudah digunakan.');if($config['demo_mode']){$id=(int)($s['meta']['next_company_id']??(max(array_column($s['companies'],'id'))+1));$row=['id'=>$id,'code'=>$code,'name'=>$name,'type'=>$type,'color'=>'violet'];$s['companies'][]=$row;$s['meta']['next_company_id']=$id+1;saveStore($s);writeAudit('company.created',['id'=>$id,'code'=>$code]);return $row;}$pdo=db();$st=$pdo->prepare("INSERT INTO companies(code,name,business_type,is_active) VALUES(?,?,?,1)");$st->execute([$code,$name,$type]);$row=['id'=>(int)$pdo->lastInsertId(),'code'=>$code,'name'=>$name,'type'=>$type];writeAudit('company.created',['id'=>$row['id'],'code'=>$code]);return $row; }
function createUserAccount(array $input): array { global $config;$s=loadStore();requireAbility('user.manage',$s);$name=trim((string)($input['name']??''));$email=strtolower(trim((string)($input['email']??'')));$role=(string)($input['role']??'viewer');$company=($input['company_id']??'')!==''?(int)$input['company_id']:null;$password=(string)($input['password']??'');$allowed=['group_owner','group_finance','entity_admin','auditor','viewer'];if(textLength($name)<3||!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($role,$allowed,true)||strlen($password)<12)throw new InvalidArgumentException('Data user tidak valid atau password kurang dari 12 karakter.');if($role==='entity_admin'&&!$company)throw new InvalidArgumentException('Entity Admin wajib memiliki badan usaha.');if($company&&!isset(companyMap($s)[$company]))throw new InvalidArgumentException('Badan usaha user tidak ditemukan.');foreach($s['users']??[] as $u)if(strtolower((string)$u['email'])===$email)throw new RuntimeException('Email user sudah digunakan.');$hash=password_hash($password,PASSWORD_DEFAULT);if($config['demo_mode']){$id=(int)($s['meta']['next_user_id']??(max(array_column($s['users'],'id'))+1));$row=['id'=>$id,'name'=>$name,'email'=>$email,'role'=>$role,'company_id'=>$company,'active'=>1,'password_hash'=>$hash];$s['users'][]=$row;$s['meta']['next_user_id']=$id+1;saveStore($s);writeAudit('user.created',['id'=>$id,'role'=>$role]);unset($row['password_hash']);return $row;}$pdo=db();$st=$pdo->prepare("INSERT INTO users(name,email,password_hash,role,company_id,is_active) VALUES(?,?,?,?,?,1)");$st->execute([$name,$email,$hash,$role,$company]);$row=['id'=>(int)$pdo->lastInsertId(),'name'=>$name,'email'=>$email,'role'=>$role,'company_id'=>$company];writeAudit('user.created',['id'=>$row['id'],'role'=>$role]);return $row; }
function createBudget(array $input): array { global $config;$s=loadStore();requireAbility('budget.manage',$s);$company=(int)($input['company_id']??0);$year=(int)($input['year']??date('Y'));$period=(int)($input['period']??date('n'));$amount=(float)($input['amount']??0);$account=(int)($input['account_id']??0);if(!$company||$year<2000||$period<1||$period>12||$amount<0||!$account)throw new InvalidArgumentException('Data budget tidak valid.');enforceCompanyAccess($s,$company);$am=accountMap($s);$a=$am[$account]??null;if(!$a)throw new InvalidArgumentException('Akun budget tidak ditemukan.');$owner=(int)($a['company_id']??0);if($owner!==0&&$owner!==$company)throw new RuntimeException('Akun budget bukan milik badan usaha yang dipilih.');if($config['demo_mode']){$found=false;foreach($s['budgets'] as &$b){if((int)$b['company_id']===$company&&(int)($b['fiscal_year']??$year)===$year&&(int)($b['period']??$period)===$period){$b['budget']=$amount;$b['fiscal_year']=$year;$b['period']=$period;$b['account_id']=$account;$found=true;$row=$b;break;}}unset($b);if(!$found){$row=['company_id'=>$company,'fiscal_year'=>$year,'period'=>$period,'account_id'=>$account,'budget'=>$amount];$s['budgets'][]=$row;}saveStore($s);writeAudit('budget.saved',['company_id'=>$company,'year'=>$year,'period'=>$period,'amount'=>$amount]);return $row;}$pdo=db();$st=$pdo->prepare("INSERT INTO budgets(company_id,fiscal_year,period,account_id,amount,scenario) VALUES(?,?,?,?,?,'budget') ON DUPLICATE KEY UPDATE amount=VALUES(amount)");$st->execute([$company,$year,$period,$account,$amount]);writeAudit('budget.saved',['company_id'=>$company,'year'=>$year,'period'=>$period,'amount'=>$amount]);return ['company_id'=>$company,'year'=>$year,'period'=>$period,'account_id'=>$account,'amount'=>$amount]; }
function createAsset(array $input): array { global $config;$s=loadStore();requireAbility('asset.manage',$s);$company=(int)($input['company_id']??0);$name=trim((string)($input['name']??''));$category=trim((string)($input['category']??''));$date=(string)($input['acquisition_date']??date('Y-m-d'));$cost=(float)($input['cost']??0);$life=(int)($input['useful_life_months']??0);$residual=(float)($input['residual_value']??0);if(!$company||textLength($name)<2||textLength($category)<2||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$cost<0||$life<=0||$residual<0||$residual>$cost)throw new InvalidArgumentException('Data aset tidak valid.');enforceCompanyAccess($s,$company);if($config['demo_mode']){$id=(int)($s['meta']['next_asset_id']??(count($s['assets'])+1));$acq=new DateTimeImmutable($date);$today=new DateTimeImmutable(date('Y-m-d'));$months=0;if($acq<=$today){$diff=$acq->diff($today);$months=max(0,min($life,$diff->y*12+$diff->m));}$book=max($residual,$cost-(($cost-$residual)/$life*$months));$row=['id'=>$id,'company_id'=>$company,'name'=>$name,'category'=>$category,'acquisition_date'=>$date,'cost'=>$cost,'book'=>$book,'useful_life_months'=>$life,'residual_value'=>$residual];$s['assets'][]=$row;$s['meta']['next_asset_id']=$id+1;saveStore($s);writeAudit('asset.created',['id'=>$id,'company_id'=>$company]);return $row;}$pdo=db();$code='AST-'.strtoupper(bin2hex(random_bytes(4)));$st=$pdo->prepare("INSERT INTO fixed_assets(company_id,asset_code,name,category,acquisition_date,acquisition_cost,useful_life_months,residual_value,status) VALUES(?,?,?,?,?,?,?,?, 'active')");$st->execute([$company,$code,$name,$category,$date,$cost,$life,$residual]);$row=['id'=>(int)$pdo->lastInsertId(),'company_id'=>$company,'name'=>$name,'category'=>$category,'cost'=>$cost,'book'=>$cost];writeAudit('asset.created',['id'=>$row['id'],'company_id'=>$company]);return $row; }
function createBankAccount(array $input): array { global $config;$s=loadStore();requireAbility('bank.manage',$s);$company=(int)($input['company_id']??0);$account=(int)($input['account_id']??0);$bank=trim((string)($input['bank_name']??''));$name=trim((string)($input['account_name']??''));$number=trim((string)($input['account_number']??''));if(!$company||!$account||textLength($bank)<2||textLength($name)<2||textLength($number)<4)throw new InvalidArgumentException('Data rekening bank tidak valid.');enforceCompanyAccess($s,$company);$am=accountMap($s);$a=$am[$account]??null;if(!$a||empty($a['cash']))throw new InvalidArgumentException('Rekening harus dipetakan ke akun kas/bank aktif.');$owner=(int)($a['company_id']??0);if($owner!==0&&$owner!==$company)throw new RuntimeException('Akun kas/bank bukan milik badan usaha yang dipilih.');if($config['demo_mode']){$id=(int)($s['meta']['next_bank_account_id']??1);$row=['id'=>$id,'company_id'=>$company,'account_id'=>$account,'bank_name'=>$bank,'account_name'=>$name,'account_number'=>$number,'active'=>1];$s['bank_accounts'][]=$row;$s['meta']['next_bank_account_id']=$id+1;saveStore($s);writeAudit('bank_account.created',['id'=>$id,'company_id'=>$company]);return $row;}$pdo=db();$st=$pdo->prepare("INSERT INTO bank_accounts(company_id,account_id,bank_name,account_name,account_number,is_active) VALUES(?,?,?,?,?,1)");$st->execute([$company,$account,$bank,$name,$number]);$row=['id'=>(int)$pdo->lastInsertId(),'company_id'=>$company,'account_id'=>$account,'bank_name'=>$bank,'account_name'=>$name,'account_number'=>$number];writeAudit('bank_account.created',['id'=>$row['id'],'company_id'=>$company]);return $row; }
function createBranch(array $input): array {
    global $config;
    $s=loadStore();requireAbility('company.manage',$s);
    $company=(int)($input['company_id']??0);$code=strtoupper(trim((string)($input['code']??'')));$name=trim((string)($input['name']??''));$timezone=trim((string)($input['timezone']??$config['timezone']));
    if(!$company||!preg_match('/^[A-Z0-9_-]{2,30}$/',$code)||textLength($name)<2||textLength($timezone)<3)throw new InvalidArgumentException('Data cabang tidak valid.');
    enforceCompanyAccess($s,$company);
    if($config['demo_mode']){
        foreach($s['branches']??[] as $b)if((int)$b['company_id']===$company&&strtoupper((string)$b['code'])===$code)throw new RuntimeException('Kode cabang sudah digunakan.');
        $ids=array_map('intval',array_column($s['branches']??[],'id'));$id=($ids?max($ids):0)+1;
        $row=['id'=>$id,'company_id'=>$company,'code'=>$code,'name'=>$name,'timezone'=>$timezone,'active'=>1];$s['branches'][]=$row;saveStore($s);writeAudit('branch.created',['id'=>$id,'company_id'=>$company]);return$row;
    }
    $pdo=db();$st=$pdo->prepare("INSERT INTO branches(company_id,code,name,timezone,is_active) VALUES(?,?,?,?,1) ON DUPLICATE KEY UPDATE name=VALUES(name),timezone=VALUES(timezone),is_active=1");$st->execute([$company,$code,$name,$timezone]);
    $id=(int)$pdo->lastInsertId();if(!$id){$q=$pdo->prepare("SELECT id FROM branches WHERE company_id=? AND code=?");$q->execute([$company,$code]);$id=(int)$q->fetchColumn();}
    writeAudit('branch.created',['id'=>$id,'company_id'=>$company]);return['id'=>$id,'company_id'=>$company,'code'=>$code,'name'=>$name,'timezone'=>$timezone,'active'=>1];
}
function createDepartment(array $input): array {
    global $config;
    $s=loadStore();requireAbility('company.manage',$s);
    $company=(int)($input['company_id']??0);$branch=(int)($input['branch_id']??0);$code=strtoupper(trim((string)($input['code']??'')));$name=trim((string)($input['name']??''));$cost=strtoupper(trim((string)($input['cost_center_code']??'')));$profit=strtoupper(trim((string)($input['profit_center_code']??'')));
    if(!$company||!$branch||!preg_match('/^[A-Z0-9_-]{2,30}$/',$code)||textLength($name)<2)throw new InvalidArgumentException('Data departemen tidak valid.');
    enforceCompanyAccess($s,$company);$branchRow=null;foreach($s['branches']??[] as$b)if((int)$b['id']===$branch)$branchRow=$b;if(!$branchRow||(int)$branchRow['company_id']!==$company)throw new RuntimeException('Cabang tidak berada pada badan usaha yang dipilih.');
    if($config['demo_mode']){
        foreach($s['departments']??[] as$d)if((int)$d['company_id']===$company&&strtoupper((string)$d['code'])===$code)throw new RuntimeException('Kode departemen sudah digunakan.');
        $ids=array_map('intval',array_column($s['departments']??[],'id'));$id=($ids?max($ids):0)+1;
        $row=['id'=>$id,'company_id'=>$company,'branch_id'=>$branch,'code'=>$code,'name'=>$name,'cost_center_code'=>$cost?:null,'profit_center_code'=>$profit?:null,'active'=>1];$s['departments'][]=$row;saveStore($s);writeAudit('department.created',['id'=>$id,'company_id'=>$company,'branch_id'=>$branch]);return$row;
    }
    $pdo=db();$st=$pdo->prepare("INSERT INTO departments(company_id,branch_id,code,name,cost_center_code,profit_center_code,is_active) VALUES(?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE branch_id=VALUES(branch_id),name=VALUES(name),cost_center_code=VALUES(cost_center_code),profit_center_code=VALUES(profit_center_code),is_active=1");$st->execute([$company,$branch,$code,$name,$cost?:null,$profit?:null]);
    $id=(int)$pdo->lastInsertId();if(!$id){$q=$pdo->prepare("SELECT id FROM departments WHERE company_id=? AND code=?");$q->execute([$company,$code]);$id=(int)$q->fetchColumn();}
    writeAudit('department.created',['id'=>$id,'company_id'=>$company,'branch_id'=>$branch]);return['id'=>$id,'company_id'=>$company,'branch_id'=>$branch,'code'=>$code,'name'=>$name,'cost_center_code'=>$cost?:null,'profit_center_code'=>$profit?:null,'active'=>1];
}
function trialBalance(array $s,?string $period=null): array { return (new \Nexa\Legacy\EnterpriseFacade())->trialBalance($s,$period); }
function balanceSheetSummary(array $s): array { return (new \Nexa\Legacy\EnterpriseFacade())->balanceSheet($s); }
function maskAccountNumber(?string $number): string { $number=trim((string)$number);if($number==='')return '-';$len=textLength($number);if($len<=4)return str_repeat('•',max(0,$len-2)).textTail($number,2);return str_repeat('•',max(4,$len-4)).textTail($number,4); }
function filterStoreByCompany(array $s,int $companyId): array { $cm=companyMap($s);if(!isset($cm[$companyId]))throw new RuntimeException('Badan usaha tidak tersedia untuk user ini.');$s['companies']=array_values(array_filter($s['companies']??[],fn($r)=>(int)$r['id']===$companyId));$s['accounts']=array_values(array_filter($s['accounts']??[],fn($r)=>(int)($r['company_id']??0)===0||(int)($r['company_id']??0)===$companyId));foreach(['branches','departments','entries','budgets','assets','invoices','bank_feed','bank_accounts','income_categories','fx_events','integration_staging','employee_advances','loan_facilities','equity_transactions','budget_scenarios'] as $k)$s[$k]=array_values(array_filter($s[$k]??[],fn($r)=>(int)($r['company_id']??0)===$companyId));$s['approvals']=array_values(array_filter($s['approvals']??[],fn($r)=>(int)($r['company_id']??0)===$companyId));$s['payments']=array_values(array_filter($s['payments']??[],fn($r)=>(int)($r['company_id']??0)===$companyId));$s['eliminations']=array_values(array_filter($s['eliminations']??[],fn($r)=>(int)($r['from_company_id']??0)===$companyId||(int)($r['to_company_id']??0)===$companyId));return $s; }
function financialReportData(?int $companyId=null): array { global $config;if(!$config['demo_mode'])return r5AttachEquityStatementProduction(r4FinancialReportDataProduction($companyId));$full=loadStore();$u=currentUser($full);$base=scopeStoreForUser($full,$u);if($companyId)$base=filterStoreByCompany($base,$companyId);$f=r4ReportFilters($companyId);$s=r4FilterDemoStore($base,$f);$period=substr($f['start'],0,7);$report=['company_id'=>$companyId,'companies'=>companyMetricsForPeriod($s,$period),'metrics'=>dashboardMetrics($s,$period),'transactions'=>transactions($s,500),'cashflow'=>cashflowTrend($s,12,$period),'trial_balance'=>trialBalance($s,$period),'balance_sheet'=>r5DemoBalanceSheet($base,$f),'intercompany'=>intercompanySummary($s),'period'=>['key'=>$period,'label'=>monthLabel($period)],'filters'=>$f];if(!$companyId)$report=r4ApplyConsolidationToReport($report,$full,$period);return r5AttachEquityStatementDemo($report,$base,$f); }
function integrationSummary(array $s): array { $counts=['received'=>0,'validated'=>0,'posted'=>0,'failed'=>0];$amount=0.0;foreach(($s['integration_staging']??[]) as $r){$st=$r['status']??'received';$counts[$st]=($counts[$st]??0)+1;$amount+=(float)($r['amount']??0);}return ['counts'=>$counts,'amount'=>$amount,'rows'=>$s['integration_staging']??[]]; }

function dashboardData(): array { global $config;if(!$config['demo_mode'])return r7DashboardDataProduction(r6DashboardDataProduction(r5DashboardDataProduction(r4DashboardDataProduction())));$full=loadStore();$u=currentUser($full);$s=scopeStoreForUser($full,$u);$period=date('Y-m');$companies=companyMetricsForPeriod($s,$period);$metrics=dashboardMetrics($s,$period);$trend=ledgerTrend($s,6,$period);$cashflow=cashflowTrend($s,6,$period);$budgets=budgetRowsForPeriod($s,$period);$users=roleCan((string)$u['role'],'user.manage')?($full['users']??[]):[$u];$demoUsers=$config['demo_mode']?($full['users']??[]):[];$bankAccounts=array_map(function($r){$r['account_number']=maskAccountNumber($r['account_number']??'');return $r;},$s['bank_accounts']??[]);return array_merge(['companies'=>$companies,'branches'=>$s['branches']??[],'departments'=>$s['departments']??[],'accounts'=>$s['accounts'],'parties'=>$s['parties']??[],'transactions'=>transactions($s),'budgets'=>$budgets,'assets'=>$s['assets'],'trend'=>$trend,'cashflow'=>$cashflow,'intercompany'=>intercompanySummary($s),'metrics'=>$metrics,'users'=>$users,'demo_users'=>$demoUsers,'periods'=>$s['periods']??[],'approvals'=>approvalSummary($s),'arap'=>arapSummary($s),'bank_reconciliation'=>bankReconciliationSummary($s),'bank_accounts'=>$bankAccounts,'income_categories'=>$s['income_categories']??[],'daily_income_recent'=>dailyIncomeRecent($s,20),'currencies'=>$s['currencies']??[],'tax_profiles'=>$s['tax_profiles']??[],'bank_import_profiles'=>$s['bank_import_profiles']??[],'settlement_batches'=>$s['settlement_batches']??[],'eliminations'=>eliminationSummary($s),'taxes'=>taxSummary($s),'fx'=>fxSummary($s),'integrations'=>integrationSummary($s),'trial_balance'=>trialBalance($s,$period),'balance_sheet'=>balanceSheetSummary($s),'current_user'=>$u,'period'=>['key'=>$period,'label'=>monthLabel($period),'revenue_growth'=>revenueGrowth($s,$period)]],r5DashboardExtras($s),r6DashboardExtras($s),r7DashboardExtras($s)); }

require_once __DIR__.'/r4_runtime.php';
require_once __DIR__.'/r5_runtime.php';
require_once __DIR__.'/r6_runtime.php';
require_once __DIR__.'/r7_runtime.php';
