<?php
declare(strict_types=1);

function r5InsertJournalInTransaction(PDO $pdo,array $s,int $company,string $date,string $description,array $lines,string $source,?int $branch=null,?int $department=null,?string $externalRef=null):array{
    r4LockPeriodDb($pdo,$company,$date);
    $norm=r4ValidateJournalLines($s,$company,$branch,$department,$lines);
    $domain=[];foreach($norm['lines'] as$l)$domain[]=new \Nexa\Accounting\JournalLine($l['account_id'],$l['debit'],$l['credit'],$l['description'],$l['intercompany_company_id'],$l['branch_id'],$l['department_id'],$l['cost_center'],$l['profit_center'],$l['project_code'],$l['transaction_currency'],$l['foreign_amount'],$l['exchange_rate'],$l['base_amount']);
    $entry=new \Nexa\Accounting\JournalEntry($company,$date,$description,$domain,$source,null,null,['external_ref'=>$externalRef],$branch,$department);
    return (new \Nexa\Infrastructure\Persistence\PdoJournalRepository($pdo))->insert($entry,(int)($_SESSION['user_id']??0));
}
function r5ExpenseCategories(array $s,int $company):array{
    global $config;if($config['demo_mode'])return array_values(array_filter($s['expense_categories']??[],fn($r)=>(int)$r['company_id']===$company&&!empty($r['active'])));
    $st=db()->prepare("SELECT id,company_id,code,name,expense_account_id,tax_profile_id,is_active active FROM expense_categories WHERE company_id=? AND is_active=1 ORDER BY code");$st->execute([$company]);return$st->fetchAll();
}
function r5CreateExpenseCategory(array $input):array{
    global $config;$s=r4ContextStore();requireAbility('expense.manage',$s);$company=(int)($input['company_id']??0);$code=strtoupper(trim((string)($input['code']??'')));$name=trim((string)($input['name']??''));$account=(int)($input['expense_account_id']??0);$tax=($input['tax_profile_id']??'')!==''?(int)$input['tax_profile_id']:null;if(!$company||!preg_match('/^[A-Z0-9._-]{2,40}$/',$code)||strlen($name)<2||!$account)throw new InvalidArgumentException('Kategori pengeluaran tidak valid.');enforceCompanyAccess($s,$company);$a=accountMap($s)[$account]??null;if(!$a||$a['type']!=='expense')throw new RuntimeException('Kategori pengeluaran wajib memakai akun expense.');$owner=(int)($a['company_id']??0);if($owner!==0&&$owner!==$company)throw new RuntimeException('Akun expense berbeda badan usaha.');if($tax&&!r4TaxProfile($s,$tax))throw new RuntimeException('Tax profile tidak ditemukan.');
    if($config['demo_mode']){foreach($s['expense_categories']??[] as$r)if((int)$r['company_id']===$company&&strtoupper($r['code'])===$code)throw new RuntimeException('Kode kategori sudah digunakan.');$id=(int)($s['meta']['next_expense_category_id']??1);$row=['id'=>$id,'company_id'=>$company,'code'=>$code,'name'=>$name,'expense_account_id'=>$account,'tax_profile_id'=>$tax,'active'=>1];$s['expense_categories'][]=$row;$s['meta']['next_expense_category_id']=$id+1;saveStore($s);r5Audit('expense_category.created',['id'=>$id,'company_id'=>$company]);return$row;}
    $pdo=db();$st=$pdo->prepare("INSERT INTO expense_categories(company_id,code,name,expense_account_id,tax_profile_id,is_active) VALUES(?,?,?,?,?,1)");$st->execute([$company,$code,$name,$account,$tax]);$row=['id'=>(int)$pdo->lastInsertId(),'company_id'=>$company,'code'=>$code,'name'=>$name,'expense_account_id'=>$account,'tax_profile_id'=>$tax,'active'=>1];writeAudit('expense_category.created',['id'=>$row['id'],'company_id'=>$company]);return$row;
}
function r5PrepareExpense(array $input,array $s):array{
    $n=(new \Nexa\Expense\DailyExpenseService())->normalize($input);enforceCompanyAccess($s,$n['company']);r4DimensionContext($s,$n['company'],$n['branch'],$n['department']);r4AssertPeriodOpen($s,$n['company'],$n['date']);$cats=[];foreach(r5ExpenseCategories($s,$n['company']) as$c)$cats[(int)$c['id']]=$c;$am=accountMap($s);$journal=[];$taxRows=[];$gross=0;
    foreach($n['normalized'] as$r){$cat=$cats[(int)$r['category_id']]??null;if(!$cat)throw new RuntimeException('Kategori pengeluaran tidak ditemukan/aktif.');$aid=(int)$cat['expense_account_id'];$a=$am[$aid]??null;if(!$a||$a['type']!=='expense')throw new RuntimeException('Mapping akun kategori pengeluaran tidak valid.');$tp=r4TaxProfile($s,$r['tax_profile_id']??$cat['tax_profile_id']??null);$amount=(int)$r['amount'];$base=$amount;$tax=0;$mode=$r['tax_mode'];if($tp&&$mode!=='none'&&(float)$tp['rate']>0){$rate=(float)$tp['rate'];if($mode==='inclusive'){$base=(int)round($amount/(1+$rate/100));$tax=$amount-$base;}elseif($mode==='exclusive'){$tax=(int)round($amount*$rate/100);$base=$amount;}else throw new RuntimeException('Mode pajak pengeluaran tidak valid.');}
        $grossLine=$base+$tax;$gross+=$grossLine;$journal[]=['account_id'=>$aid,'debit'=>$base,'credit'=>0,'description'=>$r['description']?:$cat['name'],'branch_id'=>$n['branch'],'department_id'=>$n['department'],'transaction_currency'=>$n['currency'],'exchange_rate'=>$n['rate'],'base_amount'=>$base];if($tax>0){$taxAid=(int)($tp['input_account_id']??0);if(!$taxAid)throw new RuntimeException('Tax profile tidak memiliki akun PPN Masukan.');$journal[]=['account_id'=>$taxAid,'debit'=>$tax,'credit'=>0,'description'=>'Pajak masukan '.$cat['name'],'branch_id'=>$n['branch'],'department_id'=>$n['department'],'transaction_currency'=>$n['currency'],'exchange_rate'=>$n['rate'],'base_amount'=>$tax];$taxRows[]=['tax_profile_id'=>(int)$tp['id'],'tax_base'=>$base,'tax_amount'=>$tax,'tax_code'=>$tp['code']??null];}}
    if($gross!==$n['paymentTotal'])throw new RuntimeException('Total pembayaran harus sama dengan total pengeluaran + pajak ('.money($gross).').');
    foreach($n['payNorm'] as$p){$a=$am[(int)$p['account_id']]??null;if(!$a||empty($a['cash']))throw new RuntimeException('Sumber pembayaran wajib akun Kas/Bank.');$owner=(int)($a['company_id']??0);if($owner!==0&&$owner!==$n['company'])throw new RuntimeException('Akun pembayaran berbeda badan usaha.');$journal[]=['account_id'=>(int)$p['account_id'],'debit'=>0,'credit'=>(int)$p['amount'],'description'=>'Pembayaran '.$p['method'].' '.$p['reference'],'branch_id'=>$n['branch'],'department_id'=>$n['department'],'transaction_currency'=>$n['currency'],'exchange_rate'=>$n['rate'],'base_amount'=>(int)$p['amount']];}
    return $n+['journal_lines'=>$journal,'tax_rows'=>$taxRows,'gross'=>$gross];
}
function r5PostDailyExpense(array $input,bool $internalApproved=false):array{
    global $config;$s=r4ContextStore();requireAbility('expense.manage',$s);$p=r5PrepareExpense($input,$s);$policy=r4ApprovalPolicy($s,$p['company'],'expense',$p['gross']);$payload=$input+['kind'=>'r5_daily_expense'];if($policy['required']&&!$internalApproved){$a=r4CreateApproval($payload,$p['company'],$p['date'],$p['description'],$p['gross'],'expense',$policy['min_approvers'],$policy['roles']??[],$policy['id']??null,$policy['require_distinct']??true);return['approval_required'=>true,'approval'=>$a,'amount'=>$p['gross']];}
    if($config['demo_mode']){$entry=r4PostMultiLineJournal(['company_id'=>$p['company'],'branch_id'=>$p['branch'],'department_id'=>$p['department'],'date'=>$p['date'],'description'=>$p['description'],'source'=>'daily_expense','lines'=>$p['journal_lines']],true);$s=loadStore();foreach($p['tax_rows'] as$t){$id=(int)($s['meta']['next_tax_transaction_id']??1);$s['tax_transactions'][]=['id'=>$id,'company_id'=>$p['company'],'tax_profile_id'=>$t['tax_profile_id'],'journal_id'=>$entry['id'],'transaction_date'=>$p['date'],'filing_period'=>substr($p['date'],0,7),'tax_base'=>$t['tax_base'],'tax_amount'=>$t['tax_amount'],'direction'=>'input','tax_code'=>$t['tax_code'],'status'=>'open'];$s['meta']['next_tax_transaction_id']=$id+1;}saveStore($s);r5Audit('expense.posted',['journal_id'=>$entry['id'],'amount'=>$p['gross']]);return$entry+['amount'=>$p['gross']];}
    $pdo=db();$pdo->beginTransaction();try{$entry=r5InsertJournalInTransaction($pdo,$s,$p['company'],$p['date'],$p['description'],$p['journal_lines'],'daily_expense',$p['branch'],$p['department']);$taxSt=$pdo->prepare("INSERT INTO tax_transactions(company_id,tax_profile_id,journal_id,tax_code,transaction_date,filing_period,tax_base,tax_amount,direction,status) VALUES(?,?,?,?,?,?,?,?, 'input','open')");foreach($p['tax_rows'] as$t)$taxSt->execute([$p['company'],$t['tax_profile_id'],$entry['id'],$t['tax_code'],$p['date'],substr($p['date'],0,7),$t['tax_base'],$t['tax_amount']]);(new \Nexa\Audit\TransactionalAuditService($pdo))->record('expense.posted','journal',(string)$entry['id'],['amount'=>$p['gross']],(int)($_SESSION['user_id']??0),$p['company']);r4EnqueueOutboxDb($pdo,$p['company'],'expense.posted','journal',(string)$entry['id'],['journal_id'=>$entry['id'],'amount'=>$p['gross']]);$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}r5Audit('expense.posted',['journal_id'=>$entry['id'],'amount'=>$p['gross']]);return$entry+['amount'=>$p['gross']];
}
function r5PostOpeningBalance(array $input):array{
    global $config;$s=r4ContextStore();requireAbility('onboarding.manage',$s);$n=(new \Nexa\Onboarding\OpeningBalanceService())->normalize($input);enforceCompanyAccess($s,$n['company']);r4AssertPeriodOpen($s,$n['company'],$n['date']);foreach($n['normalized'] as$l){$a=accountMap($s)[$l['account_id']]??null;if(!$a)throw new RuntimeException('Akun saldo awal tidak ditemukan.');$owner=(int)($a['company_id']??0);if($owner!==0&&$owner!==$n['company'])throw new RuntimeException('Akun saldo awal berbeda badan usaha.');}
    if($config['demo_mode']){foreach($s['opening_balance_batches']??[] as$b)if((int)$b['company_id']===$n['company']&&(int)$b['fiscal_year']===$n['year']&&$b['status']==='posted')throw new RuntimeException('Saldo awal tahun ini sudah pernah diposting.');$entry=r4PostMultiLineJournal(['company_id'=>$n['company'],'date'=>$n['date'],'description'=>'Saldo awal tahun '.$n['year'],'source'=>'opening_balance','lines'=>$n['normalized']],true);$s=loadStore();$id=(int)($s['meta']['next_opening_balance_id']??1);$s['opening_balance_batches'][]=['id'=>$id,'company_id'=>$n['company'],'fiscal_year'=>$n['year'],'opening_date'=>$n['date'],'journal_id'=>$entry['id'],'total_debit'=>$n['debit'],'total_credit'=>$n['credit'],'status'=>'posted'];$s['meta']['next_opening_balance_id']=$id+1;saveStore($s);r5Audit('opening_balance.posted',['batch_id'=>$id,'journal_id'=>$entry['id']]);return['id'=>$id,'journal_id'=>$entry['id'],'status'=>'posted'];}
    $pdo=db();$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT id FROM opening_balance_batches WHERE company_id=? AND fiscal_year=? AND status='posted' FOR UPDATE");$q->execute([$n['company'],$n['year']]);if($q->fetchColumn())throw new RuntimeException('Saldo awal tahun ini sudah pernah diposting.');$entry=r5InsertJournalInTransaction($pdo,$s,$n['company'],$n['date'],'Saldo awal tahun '.$n['year'],$n['normalized'],'opening_balance');$st=$pdo->prepare("INSERT INTO opening_balance_batches(company_id,fiscal_year,opening_date,journal_id,total_debit,total_credit,status,created_by,posted_at) VALUES(?,?,?,?,?,?,'posted',?,NOW())");$st->execute([$n['company'],$n['year'],$n['date'],$entry['id'],$n['debit'],$n['credit'],$_SESSION['user_id']??null]);$id=(int)$pdo->lastInsertId();$li=$pdo->prepare("INSERT INTO opening_balance_lines(batch_id,account_id,debit,credit,description) VALUES(?,?,?,?,?)");foreach($n['normalized'] as$l)$li->execute([$id,$l['account_id'],$l['debit'],$l['credit'],$l['description']]);(new \Nexa\Audit\TransactionalAuditService($pdo))->record('opening_balance.posted','opening_balance',(string)$id,['journal_id'=>$entry['id']],(int)($_SESSION['user_id']??0),$n['company']);$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}return['id'=>$id,'journal_id'=>$entry['id'],'status'=>'posted'];
}
function r5BankTransfer(array $input,bool $internalApproved=false):array{
    global $config;$s=r4ContextStore();requireAbility('treasury.manage',$s);$n=(new \Nexa\Treasury\BankTransferService())->validate($input);enforceCompanyAccess($s,$n['company']);r4AssertPeriodOpen($s,$n['company'],$n['date']);$am=accountMap($s);foreach([$n['from'],$n['to']] as$aid){$a=$am[$aid]??null;if(!$a||empty($a['cash']))throw new RuntimeException('Transfer hanya boleh antar akun Kas/Bank.');$owner=(int)($a['company_id']??0);if($owner!==0&&$owner!==$n['company'])throw new RuntimeException('Akun Kas/Bank berbeda badan usaha.');}if($n['fee']){$a=$am[$n['feeAccount']]??null;if(!$a||$a['type']!=='expense')throw new RuntimeException('Akun biaya transfer wajib expense.');}
    $total=$n['amount']+$n['fee'];$policy=r4ApprovalPolicy($s,$n['company'],'bank_transfer',$total);$payload=$input+['kind'=>'r5_bank_transfer'];if($policy['required']&&!$internalApproved){$a=r4CreateApproval($payload,$n['company'],$n['date'],$n['description'],$total,'bank_transfer',$policy['min_approvers'],$policy['roles']??[],$policy['id']??null,$policy['require_distinct']??true);return['approval_required'=>true,'approval'=>$a,'amount'=>$total];}
    $lines=[['account_id'=>$n['to'],'debit'=>$n['amount'],'credit'=>0,'description'=>$n['description']],['account_id'=>$n['from'],'debit'=>0,'credit'=>$total,'description'=>$n['description']]];if($n['fee'])$lines[]=['account_id'=>$n['feeAccount'],'debit'=>$n['fee'],'credit'=>0,'description'=>'Biaya transfer bank'];
    if($config['demo_mode']){$entry=r4PostMultiLineJournal(['company_id'=>$n['company'],'date'=>$n['date'],'description'=>$n['description'],'source'=>'bank_transfer','external_ref'=>$n['reference'],'lines'=>$lines],true);$s=loadStore();$id=(int)($s['meta']['next_bank_transfer_id']??1);$row=['id'=>$id,'company_id'=>$n['company'],'transfer_date'=>$n['date'],'from_account_id'=>$n['from'],'to_account_id'=>$n['to'],'amount'=>$n['amount'],'fee_amount'=>$n['fee'],'fee_account_id'=>$n['feeAccount']?:null,'reference'=>$n['reference'],'description'=>$n['description'],'journal_id'=>$entry['id'],'status'=>'posted'];$s['bank_transfers'][]=$row;$s['meta']['next_bank_transfer_id']=$id+1;saveStore($s);r5Audit('bank_transfer.posted',['id'=>$id,'journal_id'=>$entry['id']]);return$row;}
    $pdo=db();$pdo->beginTransaction();try{$entry=r5InsertJournalInTransaction($pdo,$s,$n['company'],$n['date'],$n['description'],$lines,'bank_transfer',null,null,$n['reference']?:null);$st=$pdo->prepare("INSERT INTO bank_transfers(company_id,transfer_date,from_account_id,to_account_id,amount,fee_amount,fee_account_id,reference,description,journal_id,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,'posted',?)");$st->execute([$n['company'],$n['date'],$n['from'],$n['to'],$n['amount'],$n['fee'],$n['feeAccount']?:null,$n['reference']?:null,$n['description'],$entry['id'],$_SESSION['user_id']??null]);$id=(int)$pdo->lastInsertId();(new \Nexa\Audit\TransactionalAuditService($pdo))->record('bank_transfer.posted','bank_transfer',(string)$id,['journal_id'=>$entry['id'],'amount'=>$n['amount']],(int)($_SESSION['user_id']??0),$n['company']);$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}return['id'=>$id,'journal_id'=>$entry['id'],'status'=>'posted'];
}
function r5CreateForecast(array $input):array{
    global $config;$s=r4ContextStore();requireAbility('forecast.manage',$s);$company=(int)($input['company_id']??0);$branch=($input['branch_id']??'')!==''?(int)$input['branch_id']:null;$date=(string)($input['forecast_date']??'');$direction=(string)($input['direction']??'outflow');$description=trim((string)($input['description']??''));$amount=r4MoneyInt($input['amount']??0);$prob=(float)($input['probability_pct']??100);if(!$company||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||!in_array($direction,['inflow','outflow'],true)||strlen($description)<3||$amount<=0||$prob<0||$prob>100)throw new InvalidArgumentException('Data cash forecast tidak valid.');enforceCompanyAccess($s,$company);r4DimensionContext($s,$company,$branch,null);
    if($config['demo_mode']){$id=(int)($s['meta']['next_cash_forecast_id']??1);$row=['id'=>$id,'company_id'=>$company,'branch_id'=>$branch,'forecast_date'=>$date,'direction'=>$direction,'source_type'=>'manual','source_ref'=>null,'description'=>$description,'amount'=>$amount,'currency'=>'IDR','probability_pct'=>$prob,'status'=>'planned'];$s['cash_forecast_items'][]=$row;$s['meta']['next_cash_forecast_id']=$id+1;saveStore($s);return$row;}
    $pdo=db();$st=$pdo->prepare("INSERT INTO cash_forecast_items(company_id,branch_id,forecast_date,direction,description,amount,currency,probability_pct,status,created_by) VALUES(?,?,?,?,?,?,'IDR',?,'planned',?)");$st->execute([$company,$branch,$date,$direction,$description,$amount,$prob,$_SESSION['user_id']??null]);return['id'=>(int)$pdo->lastInsertId(),'status'=>'planned'];
}
function r5CreateRecurringTemplate(array $input):array{
    global $config;$s=r4ContextStore();requireAbility('recurring.manage',$s);$v=(new \Nexa\Recurring\RecurringJournalService())->validateTemplate($input);enforceCompanyAccess($s,$v['company']);$branch=($input['branch_id']??'')!==''?(int)$input['branch_id']:null;$department=($input['department_id']??'')!==''?(int)$input['department_id']:null;r4DimensionContext($s,$v['company'],$branch,$department);r4ValidateJournalLines($s,$v['company'],$branch,$department,$v['lines']);$auto=!empty($input['auto_reverse']);$days=$auto?max(1,(int)($input['reverse_after_days']??1)):null;
    if($config['demo_mode']){$id=(int)($s['meta']['next_recurring_id']??1);$row=['id'=>$id,'company_id'=>$v['company'],'branch_id'=>$branch,'department_id'=>$department,'name'=>$v['name'],'description'=>$v['description'],'frequency'=>$v['frequency'],'next_run_date'=>$v['next'],'auto_reverse'=>$auto?1:0,'reverse_after_days'=>$days,'active'=>1,'lines'=>$v['lines']];$s['recurring_journal_templates'][]=$row;$s['meta']['next_recurring_id']=$id+1;saveStore($s);return$row;}
    $pdo=db();$pdo->beginTransaction();try{$st=$pdo->prepare("INSERT INTO recurring_journal_templates(company_id,branch_id,department_id,name,description,frequency,next_run_date,auto_reverse,reverse_after_days,is_active,created_by) VALUES(?,?,?,?,?,?,?,?,?,1,?)");$st->execute([$v['company'],$branch,$department,$v['name'],$v['description'],$v['frequency'],$v['next'],$auto?1:0,$days,$_SESSION['user_id']??null]);$id=(int)$pdo->lastInsertId();$li=$pdo->prepare("INSERT INTO recurring_journal_lines(template_id,account_id,debit,credit,description) VALUES(?,?,?,?,?)");foreach($v['lines'] as$l)$li->execute([$id,$l['account_id'],$l['debit'],$l['credit'],$l['description']??null]);$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}return['id'=>$id,'status'=>'active'];
}
function r5RunRecurring(int $id,?string $runDate=null):array{
    global $config;$s=r4ContextStore();requireAbility('recurring.manage',$s);$svc=new \Nexa\Recurring\RecurringJournalService();
    if($config['demo_mode']){
        $tpl=null;foreach($s['recurring_journal_templates']??[] as$r)if((int)$r['id']===$id)$tpl=$r;
        if(!$tpl||empty($tpl['active']))throw new RuntimeException('Template recurring tidak aktif.');
        enforceCompanyAccess($s,(int)$tpl['company_id']);$date=$runDate?:$tpl['next_run_date'];
        $entry=r4PostMultiLineJournal(['company_id'=>$tpl['company_id'],'branch_id'=>$tpl['branch_id'],'department_id'=>$tpl['department_id'],'date'=>$date,'description'=>$tpl['description'],'source'=>'recurring','document_type'=>'recurring','lines'=>$tpl['lines']],false);
        $s=loadStore();$rid=(int)($s['meta']['next_recurring_run_id']??1);$posted=empty($entry['approval_required']);$due=($posted&&!empty($tpl['auto_reverse']))?date('Y-m-d',strtotime($date.' +'.max(1,(int)($tpl['reverse_after_days']??1)).' days')):null;
        $s['recurring_journal_runs'][]=['id'=>$rid,'template_id'=>$id,'scheduled_date'=>$date,'journal_id'=>$entry['id']??null,'reversal_journal_id'=>null,'reversal_due_date'=>$due,'reversal_status'=>$due?'pending':'none','status'=>$posted?'posted':'approval'];
        foreach($s['recurring_journal_templates'] as&$r)if((int)$r['id']===$id)$r['next_run_date']=$svc->nextDate($date,$r['frequency']);unset($r);
        $s['meta']['next_recurring_run_id']=$rid+1;saveStore($s);return$entry+['reversal_due_date'=>$due];
    }
    $pdo=db();$pdo->beginTransaction();try{
        $st=$pdo->prepare("SELECT * FROM recurring_journal_templates WHERE id=? AND is_active=1 FOR UPDATE");$st->execute([$id]);$tpl=$st->fetch();if(!$tpl)throw new RuntimeException('Template recurring tidak aktif.');
        enforceCompanyAccess($s,(int)$tpl['company_id']);$date=$runDate?:$tpl['next_run_date'];
        $li=$pdo->prepare("SELECT account_id,debit,credit,description FROM recurring_journal_lines WHERE template_id=? ORDER BY id");$li->execute([$id]);$lines=$li->fetchAll();
        $entry=r5InsertJournalInTransaction($pdo,$s,(int)$tpl['company_id'],$date,(string)$tpl['description'],$lines,'recurring',$tpl['branch_id']?(int)$tpl['branch_id']:null,$tpl['department_id']?(int)$tpl['department_id']:null);
        $due=!empty($tpl['auto_reverse'])?date('Y-m-d',strtotime($date.' +'.max(1,(int)($tpl['reverse_after_days']??1)).' days')):null;
        $pdo->prepare("INSERT INTO recurring_journal_runs(template_id,scheduled_date,journal_id,reversal_due_date,reversal_status,status) VALUES(?,?,?,?,?,'posted')")->execute([$id,$date,$entry['id'],$due,$due?'pending':'none']);
        $next=$svc->nextDate($date,(string)$tpl['frequency']);$pdo->prepare("UPDATE recurring_journal_templates SET next_run_date=?,last_run_at=NOW() WHERE id=?")->execute([$next,$id]);$pdo->commit();
    }catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    return$entry+['next_run_date'=>$next,'reversal_due_date'=>$due];
}
function r5ProcessRecurringReversals(?string $asOf=null,bool $internal=false):array{
    global $config;$asOf=$asOf?:date('Y-m-d');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$asOf))throw new InvalidArgumentException('Tanggal proses reversal tidak valid.');$s=r4ContextStore();if(!$internal)requireAbility('recurring.manage',$s);$done=[];
    if($config['demo_mode']){
        $runs=$s['recurring_journal_runs']??[];foreach($runs as$run){if(($run['reversal_status']??'none')!=='pending'||empty($run['reversal_due_date'])||$run['reversal_due_date']>$asOf||empty($run['journal_id']))continue;$orig=findEntry($s,(int)$run['journal_id']);if(!$orig||($orig['status']??'')!=='posted'||!empty($orig['reversed_by']))continue;enforceCompanyAccess($s,(int)$orig['company_id']);r4AssertPeriodOpen($s,(int)$orig['company_id'],$run['reversal_due_date']);$lines=[];foreach($orig['lines'] as$l)$lines[]=['account_id'=>(int)$l['account_id'],'debit'=>(float)$l['credit'],'credit'=>(float)$l['debit'],'description'=>'Auto reversal '.($l['description']??''),'branch_id'=>$l['branch_id']??($orig['branch_id']??null),'department_id'=>$l['department_id']??($orig['department_id']??null),'cost_center'=>$l['cost_center']??null,'profit_center'=>$l['profit_center']??null,'project_code'=>$l['project_code']??null,'transaction_currency'=>$l['transaction_currency']??'IDR','foreign_amount'=>$l['foreign_amount']??null,'exchange_rate'=>$l['exchange_rate']??1,'base_amount'=>$l['base_amount']??max((float)$l['debit'],(float)$l['credit'])];$rev=r4PostMultiLineJournal(['company_id'=>$orig['company_id'],'branch_id'=>$orig['branch_id']??null,'department_id'=>$orig['department_id']??null,'date'=>$run['reversal_due_date'],'description'=>'AUTO REVERSAL '.$orig['no'],'source'=>'recurring_reversal','document_type'=>'recurring_reversal','lines'=>$lines],true);$s=loadStore();foreach($s['entries'] as&$e)if((int)$e['id']===(int)$orig['id'])$e['reversed_by']=$rev['id'];elseif((int)$e['id']===(int)$rev['id'])$e['reversal_of']=$orig['id'];unset($e);foreach($s['recurring_journal_runs'] as&$r)if((int)$r['id']===(int)$run['id']){$r['reversal_journal_id']=$rev['id'];$r['reversal_status']='posted';$r['status']='reversed';}unset($r);saveStore($s);$done[]=['run_id'=>$run['id'],'journal_id'=>$rev['id']];}
        return['processed'=>count($done),'rows'=>$done];
    }
    $pdo=db();$q=$pdo->prepare("SELECT r.id run_id,r.journal_id,r.reversal_due_date,t.company_id FROM recurring_journal_runs r JOIN recurring_journal_templates t ON t.id=r.template_id WHERE r.reversal_status='pending' AND r.reversal_due_date<=? AND r.journal_id IS NOT NULL ORDER BY r.reversal_due_date,r.id LIMIT 200");$q->execute([$asOf]);foreach($q->fetchAll() as$c){$pdo->beginTransaction();try{$lock=$pdo->prepare("SELECT r.*,t.company_id,t.branch_id,t.department_id FROM recurring_journal_runs r JOIN recurring_journal_templates t ON t.id=r.template_id WHERE r.id=? FOR UPDATE");$lock->execute([$c['run_id']]);$run=$lock->fetch();if(!$run||$run['reversal_status']!=='pending'){$pdo->rollBack();continue;}enforceCompanyAccess($s,(int)$run['company_id']);$je=$pdo->prepare("SELECT * FROM journal_entries WHERE id=? FOR UPDATE");$je->execute([$run['journal_id']]);$orig=$je->fetch();if(!$orig||$orig['status']!=='posted'||!empty($orig['reversed_by']))throw new RuntimeException('Jurnal recurring tidak tersedia untuk auto reversal.');$li=$pdo->prepare("SELECT account_id,branch_id,department_id,description,debit,credit,cost_center,profit_center,project_code,transaction_currency,foreign_amount,exchange_rate,base_amount,intercompany_company_id FROM journal_lines WHERE journal_id=? ORDER BY id");$li->execute([$orig['id']]);$lines=[];foreach($li->fetchAll() as$l)$lines[]=array_merge($l,['debit'=>$l['credit'],'credit'=>$l['debit'],'description'=>'Auto reversal '.($l['description']??'')]);$rev=r5InsertJournalInTransaction($pdo,$s,(int)$run['company_id'],$run['reversal_due_date'],'AUTO REVERSAL '.$orig['journal_no'],$lines,'recurring_reversal',$run['branch_id']?(int)$run['branch_id']:null,$run['department_id']?(int)$run['department_id']:null);$pdo->prepare("UPDATE journal_entries SET reversal_of=? WHERE id=?")->execute([$orig['id'],$rev['id']]);$pdo->prepare("UPDATE journal_entries SET reversed_by=? WHERE id=?")->execute([$rev['id'],$orig['id']]);$pdo->prepare("UPDATE recurring_journal_runs SET reversal_journal_id=?,reversal_status='posted',status='reversed' WHERE id=?")->execute([$rev['id'],$run['id']]);$pdo->commit();$done[]=['run_id'=>$run['id'],'journal_id'=>$rev['id']];}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();$pdo->prepare("UPDATE recurring_journal_runs SET reversal_status='failed',error_text=? WHERE id=?")->execute([substr($e->getMessage(),0,1000),$c['run_id']]);}}
    return['processed'=>count($done),'rows'=>$done];
}
function r5YearEndClose(array $input):array{
    global $config;$s=r4ContextStore();requireAbility('year_end.close',$s);$company=(int)($input['company_id']??0);$year=(int)($input['fiscal_year']??0);$retained=(int)($input['retained_earnings_account_id']??0);if(!$company||$year<2000||!$retained)throw new InvalidArgumentException('Data year-end close tidak valid.');enforceCompanyAccess($s,$company);$a=accountMap($s)[$retained]??null;if(!$a||$a['type']!=='equity')throw new RuntimeException('Akun retained earnings wajib bertipe equity.');$end=sprintf('%04d-12-31',$year);r4AssertPeriodOpen($s,$company,$end);
    if($config['demo_mode']){foreach($s['year_end_closes']??[] as$r)if((int)$r['company_id']===$company&&(int)$r['fiscal_year']===$year&&$r['status']==='posted')throw new RuntimeException('Year-end tahun ini sudah diposting.');$am=accountMap($s);$bal=[];foreach($s['entries'] as$e){if((int)$e['company_id']!==$company||$e['status']!=='posted'||substr($e['date'],0,4)!==(string)$year||($e['source']??'')==='year_end_close')continue;foreach($e['lines'] as$l){$acc=$am[(int)$l['account_id']]??null;if(!$acc||!in_array($acc['type'],['revenue','expense'],true))continue;$id=(int)$acc['id'];$bal[$id]??=['account_id'=>$id,'type'=>$acc['type'],'balance'=>0];$bal[$id]['balance']+=lineEffect($acc,$l);}}$built=(new \Nexa\Closing\YearEndCloseService())->buildClosingLines(array_values($bal),$retained);$entry=r4PostMultiLineJournal(['company_id'=>$company,'date'=>$end,'description'=>'Year-end closing '.$year,'source'=>'year_end_close','lines'=>$built['lines']],true);$s=loadStore();$id=(int)($s['meta']['next_year_end_id']??1);$s['year_end_closes'][]=['id'=>$id,'company_id'=>$company,'fiscal_year'=>$year,'close_date'=>$end,'profit_loss_amount'=>$built['profit'],'retained_earnings_account_id'=>$retained,'journal_id'=>$entry['id'],'status'=>'posted'];$s['meta']['next_year_end_id']=$id+1;saveStore($s);return['id'=>$id,'journal_id'=>$entry['id'],'profit_loss'=>$built['profit'],'status'=>'posted'];}
    $pdo=db();for($m=1;$m<=11;$m++){ $st=$pdo->prepare("SELECT status FROM fiscal_periods WHERE company_id=? AND fiscal_year=? AND period=?");$st->execute([$company,$year,$m]);if($st->fetchColumn()!=='closed')throw new RuntimeException('Year-end membutuhkan periode 01-11 sudah closed.');}$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT id FROM year_end_closes WHERE company_id=? AND fiscal_year=? AND status='posted' FOR UPDATE");$q->execute([$company,$year]);if($q->fetchColumn())throw new RuntimeException('Year-end tahun ini sudah diposting.');$sql="SELECT a.id account_id,a.account_type type,SUM(CASE WHEN a.account_type='revenue' THEN jl.credit-jl.debit ELSE jl.debit-jl.credit END) balance FROM journal_entries je JOIN journal_lines jl ON jl.journal_id=je.id JOIN chart_accounts a ON a.id=jl.account_id WHERE je.company_id=? AND je.status='posted' AND YEAR(je.journal_date)=? AND je.source_type<>'year_end_close' AND a.account_type IN('revenue','expense') GROUP BY a.id,a.account_type";$st=$pdo->prepare($sql);$st->execute([$company,$year]);$built=(new \Nexa\Closing\YearEndCloseService())->buildClosingLines($st->fetchAll(),$retained);$entry=r5InsertJournalInTransaction($pdo,$s,$company,$end,'Year-end closing '.$year,$built['lines'],'year_end_close');$ins=$pdo->prepare("INSERT INTO year_end_closes(company_id,fiscal_year,close_date,profit_loss_amount,retained_earnings_account_id,journal_id,status,closed_by) VALUES(?,?,?,?,?,?,'posted',?)");$ins->execute([$company,$year,$end,$built['profit'],$retained,$entry['id'],$_SESSION['user_id']??null]);$id=(int)$pdo->lastInsertId();$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}return['id'=>$id,'journal_id'=>$entry['id'],'profit_loss'=>$built['profit'],'status'=>'posted'];
}
function r5ExecuteApprovedPayload(array $payload):array{return match((string)($payload['kind']??'')){'r5_daily_expense'=>r5PostDailyExpense($payload,true),'r5_bank_transfer'=>r5BankTransfer($payload,true),default=>str_starts_with((string)($payload['kind']??''),'r6_')?r6ExecuteApprovedPayload($payload):throw new RuntimeException('Payload approval R5 tidak didukung.')};}
function r5ForecastInvoiceRows(array $invoices,string $from,string $to):array{
    $rows=[];foreach($invoices as$i){$status=(string)($i['status']??'');if(!in_array($status,['open','partial'],true))continue;$due=(string)($i['due_date']??'');if($due<$from||$due>$to)continue;$open=max(0,(float)($i['amount']??0)-(float)($i['paid']??$i['paid_amount']??0));if($open<=0)continue;$type=(string)($i['type']??$i['invoice_type']??'receivable');$rows[]=['id'=>'invoice-'.($i['id']??''),'company_id'=>(int)($i['company_id']??0),'branch_id'=>$i['branch_id']??null,'forecast_date'=>$due,'direction'=>$type==='receivable'?'inflow':'outflow','source_type'=>$type==='receivable'?'receivable':'payable','source_ref'=>(string)($i['number']??$i['invoice_no']??$i['id']??''),'description'=>($type==='receivable'?'AR ':'AP ').($i['party']??$i['party_name']??'Invoice'),'amount'=>$open,'currency'=>$i['currency']??'IDR','probability_pct'=>$type==='receivable'?90:100,'status'=>'planned'];}return$rows;
}
function r5DashboardExtras(array $s):array{
    $from=date('Y-m-d');$to=date('Y-m-d',strtotime('+90 days'));$items=array_merge($s['cash_forecast_items']??[],r5ForecastInvoiceRows($s['invoices']??[],$from,$to));$forecast=(new \Nexa\Treasury\CashForecastService())->summarize($items,$from,$to);return ['expense_categories'=>$s['expense_categories']??[],'bank_transfers'=>$s['bank_transfers']??[],'opening_balance_batches'=>$s['opening_balance_batches']??[],'recurring_journal_templates'=>$s['recurring_journal_templates']??[],'recurring_journal_runs'=>$s['recurring_journal_runs']??[],'cash_forecast_items'=>$items,'cash_forecast_summary'=>$forecast,'year_end_closes'=>$s['year_end_closes']??[]];
}
function r5DashboardDataProduction(array $base):array{
    $pdo=db();$u=currentUser(loadStore());$scope=($u['role']??'')==='entity_admin'?(int)($u['company_id']??0):0;$filter=$scope?' WHERE company_id='.(int)$scope:'';
    $base['expense_categories']=$pdo->query("SELECT id,company_id,code,name,expense_account_id,tax_profile_id,is_active active FROM expense_categories".$filter." ORDER BY company_id,code")->fetchAll();$base['bank_transfers']=$pdo->query("SELECT * FROM bank_transfers".$filter." ORDER BY transfer_date DESC,id DESC LIMIT 100")->fetchAll();$base['opening_balance_batches']=$pdo->query("SELECT * FROM opening_balance_batches".$filter." ORDER BY fiscal_year DESC,id DESC")->fetchAll();$base['recurring_journal_templates']=$pdo->query("SELECT * FROM recurring_journal_templates".$filter." ORDER BY next_run_date,id")->fetchAll();$base['recurring_journal_runs']=$pdo->query("SELECT r.* FROM recurring_journal_runs r JOIN recurring_journal_templates t ON t.id=r.template_id".($scope?' WHERE t.company_id='.(int)$scope:'')." ORDER BY r.id DESC LIMIT 100")->fetchAll();$manual=$pdo->query("SELECT * FROM cash_forecast_items".$filter." ORDER BY forecast_date,id LIMIT 500")->fetchAll();$from=date('Y-m-d');$to=date('Y-m-d',strtotime('+90 days'));$invSql="SELECT id,company_id,branch_id,invoice_type,invoice_no,party_name,due_date,amount,paid_amount,status,currency FROM invoices WHERE status IN('open','partial') AND due_date BETWEEN ".$pdo->quote($from)." AND ".$pdo->quote($to).($scope?' AND company_id='.(int)$scope:'')." ORDER BY due_date,id";$inv=$pdo->query($invSql)->fetchAll();$base['cash_forecast_items']=array_merge($manual,r5ForecastInvoiceRows($inv,$from,$to));$base['cash_forecast_summary']=(new \Nexa\Treasury\CashForecastService())->summarize($base['cash_forecast_items'],$from,$to);$base['year_end_closes']=$pdo->query("SELECT * FROM year_end_closes".$filter." ORDER BY fiscal_year DESC,id DESC")->fetchAll();return$base;
}
function r5DemoBalanceStore(array $s,array $f):array{
    $s['entries']=array_values(array_filter($s['entries']??[],function($e)use($f){if(($e['status']??'')!=='posted'||(string)($e['date']??'')>$f['end'])return false;if($f['company_id']&&(int)$e['company_id']!==(int)$f['company_id'])return false;if($f['branch_id']&&(int)($e['branch_id']??0)!==(int)$f['branch_id'])return false;if($f['department_id']&&(int)($e['department_id']??0)!==(int)$f['department_id'])return false;return true;}));return$s;
}
function r5DemoBalanceSheet(array $s,array $f):array{return balanceSheetSummary(r5DemoBalanceStore($s,$f));}
function r5AttachEquityStatementDemo(array $report,array $s,array $f):array{
    $openF=$f;$openF['end']=date('Y-m-d',strtotime($f['start'].' -1 day'));$opening=$openF['end']<'1900-01-01'?0.0:(float)(r5DemoBalanceSheet($s,$openF)['equity']??0);$am=accountMap($s);$direct=0.0;foreach($s['entries']??[] as$e){if(($e['status']??'')!=='posted'||$e['date']<$f['start']||$e['date']>$f['end']||($e['source']??'')==='year_end_close')continue;if($f['company_id']&&(int)$e['company_id']!==(int)$f['company_id'])continue;if($f['branch_id']&&(int)($e['branch_id']??0)!==(int)$f['branch_id'])continue;if($f['department_id']&&(int)($e['department_id']??0)!==(int)$f['department_id'])continue;foreach($e['lines'] as$l){$a=$am[(int)$l['account_id']]??null;if($a&&$a['type']==='equity')$direct+=(float)$l['credit']-(float)$l['debit'];}}$profit=(float)($report['metrics']['profit']??0);$closing=(float)($report['balance_sheet']['equity']??0);$other=$closing-$opening-$direct-$profit;$report['equity_statement']=['opening_equity'=>$opening,'direct_equity_movement'=>$direct,'current_profit'=>$profit,'other_adjustments'=>$other,'closing_equity'=>$closing];return$report;
}
function r5AttachEquityStatementProduction(array $report):array{
    $pdo=db();$f=$report['filters']??r4ReportFilters($report['company_id']??null);$openF=$f;$openF['end']=date('Y-m-d',strtotime($f['start'].' -1 day'));$opening=(float)(r4SqlBalanceSheet($pdo,$openF)['equity']??0);$where=["je.status='posted'","je.journal_date BETWEEN ? AND ?","je.source_type<>'year_end_close'","a.account_type='equity'"];$p=[$f['start'],$f['end']];if($f['company_id']){$where[]='je.company_id=?';$p[]=$f['company_id'];}if($f['branch_id']){$where[]='COALESCE(jl.branch_id,je.branch_id)=?';$p[]=$f['branch_id'];}if($f['department_id']){$where[]='COALESCE(jl.department_id,je.department_id)=?';$p[]=$f['department_id'];}$q=$pdo->prepare("SELECT COALESCE(SUM(jl.credit-jl.debit),0) FROM journal_entries je JOIN journal_lines jl ON jl.journal_id=je.id JOIN chart_accounts a ON a.id=jl.account_id WHERE ".implode(' AND ',$where));$q->execute($p);$direct=(float)$q->fetchColumn();$profit=(float)($report['metrics']['profit']??0);$closing=(float)($report['balance_sheet']['equity']??0);$other=$closing-$opening-$direct-$profit;$report['equity_statement']=['opening_equity'=>$opening,'direct_equity_movement'=>$direct,'current_profit'=>$profit,'other_adjustments'=>$other,'closing_equity'=>$closing];return$report;
}

function r5Audit(string $action,array $payload=[]):void{writeAudit($action,$payload);}
