<?php
/** NEXA R7 group finance controls: employee advances, financing, equity, planning and alerts. */

function r7FindById(array $rows,int $id):?array{foreach($rows as$r)if((int)($r['id']??0)===$id)return$r;return null;}
function r7Account(array $s,int $id,int $company,?string $type=null,bool $cash=false):array{$a=accountMap($s)[$id]??null;if(!$a)throw new RuntimeException('Akun tidak ditemukan.');$owner=(int)($a['company_id']??0);if($owner!==0&&$owner!==$company)throw new RuntimeException('Akun berbeda badan usaha.');if($type&&($a['type']??'')!==$type)throw new RuntimeException('Tipe akun tidak sesuai.');if($cash&&empty($a['cash']))throw new RuntimeException('Akun wajib Kas/Bank.');return$a;}

function r7IssueAdvance(array $input,bool $internalApproved=false):array{
    global $config;$s=r4ContextStore();requireAbility('advance.manage',$s);$n=(new \Nexa\Advance\EmployeeAdvanceService())->issue($input);enforceCompanyAccess($s,$n['company_id']);r4AssertPeriodOpen($s,$n['company_id'],$n['advance_date']);r7Account($s,$n['advance_account_id'],$n['company_id'],'asset');r7Account($s,$n['cash_account_id'],$n['company_id'],null,true);$branch=($input['branch_id']??'')!==''?(int)$input['branch_id']:null;$dept=($input['department_id']??'')!==''?(int)$input['department_id']:null;r4DimensionContext($s,$n['company_id'],$branch,$dept);$policy=r4ApprovalPolicy($s,$n['company_id'],'advance',$n['amount']);$payload=$input+['kind'=>'r7_advance_issue'];if($policy['required']&&!$internalApproved){$a=r4CreateApproval($payload,$n['company_id'],$n['advance_date'],$n['description'],$n['amount'],'advance',$policy['min_approvers'],$policy['roles']??[],$policy['id']??null,$policy['require_distinct']??true);return['approval_required'=>true,'approval'=>$a,'amount'=>$n['amount']];}
    $lines=[['account_id'=>$n['advance_account_id'],'debit'=>$n['amount'],'credit'=>0,'description'=>$n['employee_name'],'branch_id'=>$branch,'department_id'=>$dept],['account_id'=>$n['cash_account_id'],'debit'=>0,'credit'=>$n['amount'],'description'=>'Pencairan uang muka','branch_id'=>$branch,'department_id'=>$dept]];
    if($config['demo_mode']){$j=r4PostMultiLineJournal(['company_id'=>$n['company_id'],'branch_id'=>$branch,'department_id'=>$dept,'date'=>$n['advance_date'],'description'=>$n['description'].' · '.$n['employee_name'],'source'=>'employee_advance','lines'=>$lines],true);$s=loadStore();$id=(int)($s['meta']['next_advance_id']??1);$row=['id'=>$id,'company_id'=>$n['company_id'],'branch_id'=>$branch,'department_id'=>$dept,'employee_name'=>$n['employee_name'],'advance_date'=>$n['advance_date'],'due_date'=>$n['due_date'],'amount'=>$n['amount'],'outstanding_amount'=>$n['amount'],'advance_account_id'=>$n['advance_account_id'],'cash_account_id'=>$n['cash_account_id'],'issue_journal_id'=>$j['id'],'description'=>$n['description'],'status'=>'open','created_by'=>currentUser($s)['id']??null];$s['employee_advances'][]=$row;$s['meta']['next_advance_id']=$id+1;saveStore($s);writeAudit('advance.issued',['id'=>$id,'amount'=>$n['amount']]);return$row+['journal_id'=>$j['id']];}
    $pdo=db();$pdo->beginTransaction();try{$j=r5InsertJournalInTransaction($pdo,$s,$n['company_id'],$n['advance_date'],$n['description'].' · '.$n['employee_name'],$lines,'employee_advance',$branch,$dept);$st=$pdo->prepare("INSERT INTO employee_advances(company_id,branch_id,department_id,employee_name,advance_date,due_date,amount,outstanding_amount,advance_account_id,cash_account_id,issue_journal_id,description,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'open',?)");$st->execute([$n['company_id'],$branch,$dept,$n['employee_name'],$n['advance_date'],$n['due_date'],$n['amount'],$n['amount'],$n['advance_account_id'],$n['cash_account_id'],$j['id'],$n['description'],$_SESSION['user_id']??null]);$id=(int)$pdo->lastInsertId();(new \Nexa\Audit\TransactionalAuditService($pdo))->record('advance.issued','employee_advance',(string)$id,['amount'=>$n['amount']],(int)($_SESSION['user_id']??0),$n['company_id']);$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}return['id'=>$id,'company_id'=>$n['company_id'],'amount'=>$n['amount'],'outstanding_amount'=>$n['amount'],'status'=>'open','journal_id'=>$j['id']];
}

function r7SettleAdvance(array $input):array{
    global $config;$s=r4ContextStore();requireAbility('advance.manage',$s);$id=(int)($input['advance_id']??0);if($id<=0)throw new InvalidArgumentException('Uang muka tidak valid.');$advance=r7FindById($s['employee_advances']??[],$id);if(!$advance&&!$config['demo_mode']){$q=db()->prepare('SELECT * FROM employee_advances WHERE id=?');$q->execute([$id]);$advance=$q->fetch()?:null;}if(!$advance)throw new RuntimeException('Uang muka tidak ditemukan.');enforceCompanyAccess($s,(int)$advance['company_id']);if(!in_array((string)$advance['status'],['open','partial'],true))throw new RuntimeException('Uang muka sudah selesai.');$n=(new \Nexa\Advance\EmployeeAdvanceService())->settlement($advance,$input);r4AssertPeriodOpen($s,(int)$advance['company_id'],$n['settlement_date']);r7Account($s,$n['expense_account_id'],(int)$advance['company_id'],'expense');r7Account($s,$n['cash_account_id'],(int)$advance['company_id'],null,true);$lines=[];if($n['expense_amount']>0)$lines[]=['account_id'=>$n['expense_account_id'],'debit'=>$n['expense_amount'],'credit'=>0,'description'=>$n['description']];if($n['refund_amount']>0)$lines[]=['account_id'=>$n['cash_account_id'],'debit'=>$n['refund_amount'],'credit'=>0,'description'=>'Pengembalian uang muka'];$lines[]=['account_id'=>(int)$advance['advance_account_id'],'debit'=>0,'credit'=>(int)$advance['outstanding_amount'],'description'=>'Clearing uang muka'];if($n['reimbursement_amount']>0)$lines[]=['account_id'=>$n['cash_account_id'],'debit'=>0,'credit'=>$n['reimbursement_amount'],'description'=>'Reimbursement tambahan'];
    if($config['demo_mode']){$j=r4PostMultiLineJournal(['company_id'=>(int)$advance['company_id'],'branch_id'=>$advance['branch_id']??null,'department_id'=>$advance['department_id']??null,'date'=>$n['settlement_date'],'description'=>$n['description'].' · '.$advance['employee_name'],'source'=>'advance_settlement','lines'=>$lines],true);$s=loadStore();$sid=(int)($s['meta']['next_advance_settlement_id']??1);$s['employee_advance_settlements'][]=['id'=>$sid,'advance_id'=>$id]+$n+['journal_id'=>$j['id']];foreach($s['employee_advances'] as&$r)if((int)$r['id']===$id){$r['outstanding_amount']=0;$r['status']='settled';$advance=$r;}unset($r);$s['meta']['next_advance_settlement_id']=$sid+1;saveStore($s);writeAudit('advance.settled',['id'=>$id,'journal_id'=>$j['id']]);return$advance+['settlement_id'=>$sid,'journal_id'=>$j['id']];}
    $pdo=db();$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT * FROM employee_advances WHERE id=? FOR UPDATE');$q->execute([$id]);$dbAdvance=$q->fetch();if(!$dbAdvance||!in_array($dbAdvance['status'],['open','partial'],true))throw new RuntimeException('Uang muka tidak tersedia untuk settlement.');$j=r5InsertJournalInTransaction($pdo,$s,(int)$dbAdvance['company_id'],$n['settlement_date'],$n['description'].' · '.$dbAdvance['employee_name'],$lines,'advance_settlement',$dbAdvance['branch_id']?:(null),$dbAdvance['department_id']?:(null));$st=$pdo->prepare('INSERT INTO employee_advance_settlements(advance_id,settlement_date,expense_amount,refund_amount,reimbursement_amount,expense_account_id,cash_account_id,journal_id,description,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)');$st->execute([$id,$n['settlement_date'],$n['expense_amount'],$n['refund_amount'],$n['reimbursement_amount'],$n['expense_account_id'],$n['cash_account_id'],$j['id'],$n['description'],$_SESSION['user_id']??null]);$sid=(int)$pdo->lastInsertId();$pdo->prepare("UPDATE employee_advances SET outstanding_amount=0,status='settled' WHERE id=?")->execute([$id]);(new \Nexa\Audit\TransactionalAuditService($pdo))->record('advance.settled','employee_advance',(string)$id,['journal_id'=>$j['id']],(int)($_SESSION['user_id']??0),(int)$dbAdvance['company_id']);$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}return['id'=>$id,'status'=>'settled','settlement_id'=>$sid,'journal_id'=>$j['id']];
}

function r7CreateLoan(array $input,bool $internalApproved=false):array{
    global $config;$s=r4ContextStore();requireAbility('financing.manage',$s);$n=(new \Nexa\Financing\LoanService())->facility($input);enforceCompanyAccess($s,$n['company_id']);r4AssertPeriodOpen($s,$n['company_id'],$n['start_date']);r7Account($s,$n['liability_account_id'],$n['company_id'],'liability');r7Account($s,$n['cash_account_id'],$n['company_id'],null,true);r7Account($s,$n['interest_expense_account_id'],$n['company_id'],'expense');$policy=r4ApprovalPolicy($s,$n['company_id'],'financing',$n['principal']);$payload=$input+['kind'=>'r7_loan_create'];if($policy['required']&&!$internalApproved){$a=r4CreateApproval($payload,$n['company_id'],$n['start_date'],'Pencairan pinjaman '.$n['lender_name'],$n['principal'],'financing',$policy['min_approvers'],$policy['roles']??[],$policy['id']??null,$policy['require_distinct']??true);return['approval_required'=>true,'approval'=>$a,'amount'=>$n['principal']];}$lines=[['account_id'=>$n['cash_account_id'],'debit'=>$n['principal'],'credit'=>0,'description'=>'Pencairan pinjaman'],['account_id'=>$n['liability_account_id'],'debit'=>0,'credit'=>$n['principal'],'description'=>'Pokok pinjaman']];
    if($config['demo_mode']){$j=r4PostMultiLineJournal(['company_id'=>$n['company_id'],'date'=>$n['start_date'],'description'=>'Pinjaman '.$n['lender_name'],'source'=>'loan_disbursement','lines'=>$lines],true);$s=loadStore();$id=(int)($s['meta']['next_loan_id']??1);$row=['id'=>$id]+$n+['outstanding_principal'=>$n['principal'],'disbursement_journal_id'=>$j['id'],'status'=>'active'];$s['loan_facilities'][]=$row;$s['meta']['next_loan_id']=$id+1;saveStore($s);writeAudit('loan.created',['id'=>$id,'principal'=>$n['principal']]);return$row+['journal_id'=>$j['id']];}
    $pdo=db();$pdo->beginTransaction();try{$j=r5InsertJournalInTransaction($pdo,$s,$n['company_id'],$n['start_date'],'Pinjaman '.$n['lender_name'],$lines,'loan_disbursement');$st=$pdo->prepare("INSERT INTO loan_facilities(company_id,lender_name,reference_no,start_date,maturity_date,principal,outstanding_principal,annual_interest_rate,liability_account_id,cash_account_id,interest_expense_account_id,disbursement_journal_id,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'active',?)");$st->execute([$n['company_id'],$n['lender_name'],$n['reference_no'],$n['start_date'],$n['maturity_date'],$n['principal'],$n['principal'],$n['annual_interest_rate'],$n['liability_account_id'],$n['cash_account_id'],$n['interest_expense_account_id'],$j['id'],$_SESSION['user_id']??null]);$id=(int)$pdo->lastInsertId();$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}return['id'=>$id,'status'=>'active','outstanding_principal'=>$n['principal'],'journal_id'=>$j['id']];
}

function r7PayLoan(array $input,bool $internalApproved=false):array{
    global $config;$s=r4ContextStore();requireAbility('financing.manage',$s);$id=(int)($input['loan_id']??0);$loan=r7FindById($s['loan_facilities']??[],$id);if(!$loan&&!$config['demo_mode']){$q=db()->prepare('SELECT * FROM loan_facilities WHERE id=?');$q->execute([$id]);$loan=$q->fetch()?:null;}if(!$loan)throw new RuntimeException('Pinjaman tidak ditemukan.');enforceCompanyAccess($s,(int)$loan['company_id']);$n=(new \Nexa\Financing\LoanService())->payment($loan,$input);r4AssertPeriodOpen($s,(int)$loan['company_id'],$n['payment_date']);r7Account($s,$n['cash_account_id'],(int)$loan['company_id'],null,true);$policy=r4ApprovalPolicy($s,(int)$loan['company_id'],'financing',$n['total_amount']);$payload=$input+['kind'=>'r7_loan_payment'];if($policy['required']&&!$internalApproved){$a=r4CreateApproval($payload,(int)$loan['company_id'],$n['payment_date'],'Pembayaran pinjaman '.$loan['lender_name'],$n['total_amount'],'financing',$policy['min_approvers'],$policy['roles']??[],$policy['id']??null,$policy['require_distinct']??true);return['approval_required'=>true,'approval'=>$a,'amount'=>$n['total_amount']];}$lines=[];if($n['principal_amount']>0)$lines[]=['account_id'=>(int)$loan['liability_account_id'],'debit'=>$n['principal_amount'],'credit'=>0,'description'=>'Pembayaran pokok'];if($n['interest_amount']>0)$lines[]=['account_id'=>(int)$loan['interest_expense_account_id'],'debit'=>$n['interest_amount'],'credit'=>0,'description'=>'Beban bunga'];$lines[]=['account_id'=>$n['cash_account_id'],'debit'=>0,'credit'=>$n['total_amount'],'description'=>'Pembayaran pinjaman'];
    if($config['demo_mode']){$j=r4PostMultiLineJournal(['company_id'=>(int)$loan['company_id'],'date'=>$n['payment_date'],'description'=>'Pembayaran pinjaman '.$loan['lender_name'],'source'=>'loan_payment','lines'=>$lines],true);$s=loadStore();$pid=(int)($s['meta']['next_loan_payment_id']??1);$s['loan_payments'][]=['id'=>$pid,'loan_id'=>$id]+$n+['journal_id'=>$j['id']];foreach($s['loan_facilities'] as&$r)if((int)$r['id']===$id){$r['outstanding_principal']=max(0,(int)$r['outstanding_principal']-$n['principal_amount']);if($r['outstanding_principal']===0)$r['status']='paid';$loan=$r;}unset($r);$s['meta']['next_loan_payment_id']=$pid+1;saveStore($s);return$loan+['payment_id'=>$pid,'journal_id'=>$j['id']];}
    $pdo=db();$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT * FROM loan_facilities WHERE id=? FOR UPDATE');$q->execute([$id]);$dbLoan=$q->fetch();if(!$dbLoan||$dbLoan['status']!=='active')throw new RuntimeException('Pinjaman tidak aktif.');if($n['principal_amount']>(float)$dbLoan['outstanding_principal'])throw new RuntimeException('Pokok melebihi outstanding.');$j=r5InsertJournalInTransaction($pdo,$s,(int)$dbLoan['company_id'],$n['payment_date'],'Pembayaran pinjaman '.$dbLoan['lender_name'],$lines,'loan_payment');$st=$pdo->prepare('INSERT INTO loan_payments(loan_id,payment_date,principal_amount,interest_amount,cash_account_id,reference_no,journal_id,created_by) VALUES(?,?,?,?,?,?,?,?)');$st->execute([$id,$n['payment_date'],$n['principal_amount'],$n['interest_amount'],$n['cash_account_id'],$n['reference_no'],$j['id'],$_SESSION['user_id']??null]);$pid=(int)$pdo->lastInsertId();$remaining=(float)$dbLoan['outstanding_principal']-$n['principal_amount'];$pdo->prepare("UPDATE loan_facilities SET outstanding_principal=?,status=? WHERE id=?")->execute([$remaining,$remaining<=0?'paid':'active',$id]);$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}return['id'=>$id,'payment_id'=>$pid,'outstanding_principal'=>$remaining,'status'=>$remaining<=0?'paid':'active','journal_id'=>$j['id']];
}

function r7PostEquity(array $input,bool $internalApproved=false):array{
    global $config;$s=r4ContextStore();requireAbility('equity.manage',$s);$n=(new \Nexa\Equity\EquityTransactionService())->normalize($input);enforceCompanyAccess($s,$n['company_id']);r4AssertPeriodOpen($s,$n['company_id'],$n['transaction_date']);r7Account($s,$n['cash_account_id'],$n['company_id'],null,true);r7Account($s,$n['equity_account_id'],$n['company_id'],'equity');$policy=r4ApprovalPolicy($s,$n['company_id'],'equity',$n['amount']);$payload=$input+['kind'=>'r7_equity'];if($policy['required']&&!$internalApproved){$a=r4CreateApproval($payload,$n['company_id'],$n['transaction_date'],$n['description'],$n['amount'],'equity',$policy['min_approvers'],$policy['roles']??[],$policy['id']??null,$policy['require_distinct']??true);return['approval_required'=>true,'approval'=>$a,'amount'=>$n['amount']];}$incoming=$n['transaction_type']==='capital_contribution';$lines=$incoming?[['account_id'=>$n['cash_account_id'],'debit'=>$n['amount'],'credit'=>0],['account_id'=>$n['equity_account_id'],'debit'=>0,'credit'=>$n['amount']]]:[['account_id'=>$n['equity_account_id'],'debit'=>$n['amount'],'credit'=>0],['account_id'=>$n['cash_account_id'],'debit'=>0,'credit'=>$n['amount']]];
    if($config['demo_mode']){$j=r4PostMultiLineJournal(['company_id'=>$n['company_id'],'date'=>$n['transaction_date'],'description'=>$n['description'],'source'=>'equity_transaction','lines'=>$lines],true);$s=loadStore();$id=(int)($s['meta']['next_equity_tx_id']??1);$row=['id'=>$id]+$n+['journal_id'=>$j['id']];$s['equity_transactions'][]=$row;$s['meta']['next_equity_tx_id']=$id+1;saveStore($s);return$row;}
    $pdo=db();$pdo->beginTransaction();try{$j=r5InsertJournalInTransaction($pdo,$s,$n['company_id'],$n['transaction_date'],$n['description'],$lines,'equity_transaction');$st=$pdo->prepare('INSERT INTO equity_transactions(company_id,transaction_type,transaction_date,amount,cash_account_id,equity_account_id,reference_no,description,journal_id,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)');$st->execute([$n['company_id'],$n['transaction_type'],$n['transaction_date'],$n['amount'],$n['cash_account_id'],$n['equity_account_id'],$n['reference_no'],$n['description'],$j['id'],$_SESSION['user_id']??null]);$id=(int)$pdo->lastInsertId();$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}return['id'=>$id,'journal_id'=>$j['id']]+$n;
}

function r7CreateBudgetScenario(array $input):array{
    global $config;$s=r4ContextStore();requireAbility('planning.manage',$s);$n=(new \Nexa\Planning\BudgetScenarioService())->scenario($input);enforceCompanyAccess($s,$n['company_id']);if($config['demo_mode']){foreach($s['budget_scenarios']??[] as$r)if((int)$r['company_id']===$n['company_id']&&(int)$r['fiscal_year']===$n['fiscal_year']&&$r['code']===$n['code'])throw new RuntimeException('Kode scenario sudah digunakan.');$id=(int)($s['meta']['next_budget_scenario_id']??1);$row=['id'=>$id]+$n;$s['budget_scenarios'][]=$row;$s['meta']['next_budget_scenario_id']=$id+1;saveStore($s);return$row;}$pdo=db();$st=$pdo->prepare("INSERT INTO budget_scenarios(company_id,fiscal_year,code,name,scenario_type,status,created_by) VALUES(?,?,?,?,?,'draft',?)");$st->execute([$n['company_id'],$n['fiscal_year'],$n['code'],$n['name'],$n['scenario_type'],$_SESSION['user_id']??null]);return['id'=>(int)$pdo->lastInsertId()]+$n;
}
function r7SaveBudgetScenarioLine(array $input):array{
    global $config;$s=r4ContextStore();requireAbility('planning.manage',$s);$n=(new \Nexa\Planning\BudgetScenarioService())->line($input);$scenario=r7FindById($s['budget_scenarios']??[],$n['scenario_id']);if(!$scenario&&!$config['demo_mode']){$q=db()->prepare('SELECT * FROM budget_scenarios WHERE id=?');$q->execute([$n['scenario_id']]);$scenario=$q->fetch()?:null;}if(!$scenario)throw new RuntimeException('Budget scenario tidak ditemukan.');enforceCompanyAccess($s,(int)$scenario['company_id']);r7Account($s,$n['account_id'],(int)$scenario['company_id']);if($n['branch_id']||$n['department_id'])r4DimensionContext($s,(int)$scenario['company_id'],$n['branch_id'],$n['department_id']);if($config['demo_mode']){$id=(int)($s['meta']['next_budget_scenario_line_id']??1);$found=false;foreach($s['budget_scenario_lines'] as&$r)if((int)$r['scenario_id']===$n['scenario_id']&&(int)$r['period']===$n['period']&&(int)$r['account_id']===$n['account_id']&&(int)($r['branch_id']??0)===(int)($n['branch_id']??0)&&(int)($r['department_id']??0)===(int)($n['department_id']??0)){$r=array_merge($r,$n);$row=$r;$found=true;}unset($r);if(!$found){$row=['id'=>$id]+$n;$s['budget_scenario_lines'][]=$row;$s['meta']['next_budget_scenario_line_id']=$id+1;}saveStore($s);return$row;}$pdo=db();$st=$pdo->prepare('INSERT INTO budget_scenario_lines(scenario_id,branch_id,department_id,period,account_id,amount) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE amount=VALUES(amount)');$st->execute([$n['scenario_id'],$n['branch_id'],$n['department_id'],$n['period'],$n['account_id'],$n['amount']]);return$n;
}

function r7ExecuteApprovedPayload(array $payload):array{return match((string)($payload['kind']??'')){'r7_advance_issue'=>r7IssueAdvance($payload,true),'r7_loan_create'=>r7CreateLoan($payload,true),'r7_loan_payment'=>r7PayLoan($payload,true),'r7_equity'=>r7PostEquity($payload,true),default=>throw new RuntimeException('Payload approval R7 tidak didukung.')};}

function r7Notifications(array $s):array{return (new \Nexa\Notifications\NotificationService())->generate($s,date('Y-m-d'));}
function r7ManagementKpis(array $s):array{$m=dashboardMetrics($s,date('Y-m'));$ar=arapSummary($s);$loan=array_sum(array_map(fn($r)=>(float)($r['outstanding_principal']??0),$s['loan_facilities']??[]));return (new \Nexa\Reports\ManagementKpiService())->calculate((float)$m['revenue'],(float)$m['expense'],(float)$m['cash'],(float)($ar['receivable']??0),(float)($ar['payable']??0),$loan);}
function r7DashboardExtras(array $s):array{return ['employee_advances'=>$s['employee_advances']??[],'employee_advance_settlements'=>$s['employee_advance_settlements']??[],'loan_facilities'=>$s['loan_facilities']??[],'loan_payments'=>$s['loan_payments']??[],'equity_transactions'=>$s['equity_transactions']??[],'budget_scenarios'=>$s['budget_scenarios']??[],'budget_scenario_lines'=>$s['budget_scenario_lines']??[],'notifications'=>r7Notifications($s),'management_kpis'=>r7ManagementKpis($s)];}
function r7DashboardDataProduction(array $base):array{$pdo=db();$u=currentUser(loadStore());$scope=($u['role']??'')==='entity_admin'?(int)($u['company_id']??0):0;$f=$scope?' WHERE company_id='.(int)$scope:'';$base['employee_advances']=$pdo->query('SELECT * FROM employee_advances'.$f.' ORDER BY advance_date DESC,id DESC LIMIT 300')->fetchAll();$base['employee_advance_settlements']=$pdo->query('SELECT s.* FROM employee_advance_settlements s JOIN employee_advances a ON a.id=s.advance_id'.($scope?' WHERE a.company_id='.(int)$scope:'').' ORDER BY s.settlement_date DESC,s.id DESC LIMIT 300')->fetchAll();$base['loan_facilities']=$pdo->query('SELECT * FROM loan_facilities'.$f.' ORDER BY maturity_date,id DESC LIMIT 300')->fetchAll();$base['loan_payments']=$pdo->query('SELECT p.* FROM loan_payments p JOIN loan_facilities l ON l.id=p.loan_id'.($scope?' WHERE l.company_id='.(int)$scope:'').' ORDER BY p.payment_date DESC,p.id DESC LIMIT 300')->fetchAll();$base['equity_transactions']=$pdo->query('SELECT * FROM equity_transactions'.$f.' ORDER BY transaction_date DESC,id DESC LIMIT 300')->fetchAll();$base['budget_scenarios']=$pdo->query('SELECT * FROM budget_scenarios'.$f.' ORDER BY fiscal_year DESC,id DESC LIMIT 200')->fetchAll();$base['budget_scenario_lines']=$pdo->query('SELECT l.* FROM budget_scenario_lines l JOIN budget_scenarios s ON s.id=l.scenario_id'.($scope?' WHERE s.company_id='.(int)$scope:'').' ORDER BY l.id DESC LIMIT 1000')->fetchAll();$base['notifications']=(new \Nexa\Notifications\NotificationService())->generate($base,date('Y-m-d'));$loan=array_sum(array_map(fn($r)=>(float)($r['outstanding_principal']??0),$base['loan_facilities']));$base['management_kpis']=(new \Nexa\Reports\ManagementKpiService())->calculate((float)($base['metrics']['revenue']??0),(float)($base['metrics']['expense']??0),(float)($base['metrics']['cash']??0),(float)($base['arap']['receivable']??0),(float)($base['arap']['payable']??0),$loan);return$base;}
