<?php
declare(strict_types=1);

function nexaXml(string $v): string { return htmlspecialchars($v, ENT_XML1|ENT_COMPAT, 'UTF-8'); }
function nexaColName(int $n): string { $s=''; while($n>0){$n--; $s=chr(65+($n%26)).$s; $n=intdiv($n,26);} return $s; }
function nexaDosTimeDate(?int $ts=null): array { $ts=$ts??time();$p=getdate($ts);$year=max(1980,(int)$p['year']);$date=(($year-1980)<<9)|((int)$p['mon']<<5)|(int)$p['mday'];$time=((int)$p['hours']<<11)|((int)$p['minutes']<<5)|intdiv((int)$p['seconds'],2);return[$time,$date]; }
function nexaWriteZipStore(string $path,array $files): void {
    [$tm,$dt]=nexaDosTimeDate();$body='';$central='';$offset=0;$count=0;
    foreach($files as$name=>$content){$name=str_replace('\\','/',(string)$name);$content=(string)$content;$len=strlen($content);$crc=crc32($content);$local=pack('VvvvvvVVVvv',0x04034b50,20,0,0,$tm,$dt,$crc,$len,$len,strlen($name),0).$name.$content;$body.=$local;$central.=pack('VvvvvvvVVVvvvvvVV',0x02014b50,20,20,0,0,$tm,$dt,$crc,$len,$len,strlen($name),0,0,0,0,0,$offset).$name;$offset+=strlen($local);$count++;}
    $end=pack('VvvvvVVv',0x06054b50,0,0,$count,$count,strlen($central),strlen($body),0);if(file_put_contents($path,$body.$central.$end)===false)throw new RuntimeException('Gagal menulis file XLSX.');
}
function nexaWriteXlsx(string $path,array $headers,array $rows,string $title='NEXA Report'): void {
    $zip=null;if(class_exists('ZipArchive')){$zip=new ZipArchive();if($zip->open($path,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true)throw new RuntimeException('Gagal membuat file XLSX.');}
    $all=array_merge([$headers],$rows); $sheet=[];
    foreach($all as $ri=>$row){$cells=[];foreach(array_values($row) as $ci=>$v){$ref=nexaColName($ci+1).($ri+1);if(is_int($v)||is_float($v)||(is_string($v)&&is_numeric($v)&&!preg_match('/^0\d+$/',$v))){$cells[]='<c r="'.$ref.'"><v>'.(0+$v).'</v></c>';}else{$cells[]='<c r="'.$ref.'" t="inlineStr"><is><t>'.nexaXml((string)$v).'</t></is></c>';}}$sheet[]='<row r="'.($ri+1).'">'.implode('',$cells).'</row>';}
    $created=gmdate('Y-m-d\TH:i:s\Z');
    $files=[
      '[Content_Types].xml'=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>',
      '_rels/.rels'=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>',
      'xl/workbook.xml'=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Report" sheetId="1" r:id="rId1"/></sheets></workbook>',
      'xl/_rels/workbook.xml.rels'=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>',
      'xl/worksheets/sheet1.xml'=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>'.implode('',$sheet).'</sheetData><autoFilter ref="A1:'.nexaColName(max(1,count($headers))).max(1,count($all)).'"/></worksheet>',
      'docProps/core.xml'=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>'.nexaXml($title).'</dc:title><dc:creator>NEXA Group Finance</dc:creator><dcterms:created xsi:type="dcterms:W3CDTF">'.$created.'</dcterms:created></cp:coreProperties>',
      'docProps/app.xml'=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>NEXA Group Finance</Application></Properties>'
    ];
    if($zip){foreach($files as$n=>$c)$zip->addFromString($n,$c);$zip->close();}else nexaWriteZipStore($path,$files);
}
function nexaPdfEscape(string $s): string { $s=preg_replace('/[^\x20-\x7E]/','?', $s)??$s;return str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$s); }
function nexaBuildPdf(array $headers,array $rows,string $title='NEXA Group Finance Report'): string {
    $lines=[$title,'Generated: '.date('Y-m-d H:i:s'),str_repeat('-',110),implode(' | ',$headers),str_repeat('-',110)];
    foreach($rows as$r){$parts=[];foreach($r as$v){$t=(string)$v;if(strlen($t)>28)$t=substr($t,0,25).'...';$parts[]=$t;}$lines[]=implode(' | ',$parts);}
    $pages=array_chunk($lines,45);$objects=[];$pageIds=[];$fontId=3;$next=4;
    foreach($pages as$page){$content="BT\n/F1 8 Tf\n36 806 Td\n";foreach($page as$i=>$line){if($i)$content.="0 -16 Td\n";$content.='('.nexaPdfEscape($line).") Tj\n";}$content.="ET";$contentId=$next++;$pageId=$next++;$objects[$contentId]="<< /Length ".strlen($content)." >>\nstream\n$content\nendstream";$objects[$pageId]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 $fontId 0 R >> >> /Contents $contentId 0 R >>";$pageIds[]=$pageId;}
    $objects[1]='<< /Type /Catalog /Pages 2 0 R >>';$kids=implode(' ',array_map(fn($id)=>$id.' 0 R',$pageIds));$objects[2]='<< /Type /Pages /Kids ['.$kids.'] /Count '.count($pageIds).' >>';$objects[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';ksort($objects);$pdf="%PDF-1.4\n";$offset=[0];foreach($objects as$id=>$obj){$offset[$id]=strlen($pdf);$pdf.="$id 0 obj\n$obj\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($objects));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf("%010d 00000 n \n",$offset[$i]??0);$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";return$pdf;
}
